In [1]:
# packages

import numpy as np
import pandas as pd
import scipy as sp

In [2]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [3]:
!pip


Usage:   
  pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  search                      Search PyPI for packages.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring
                              environment variables and user conf

In [4]:
sp.misc

AttributeError: module 'scipy' has no attribute 'misc'

In [5]:
from scipy import misc

In [6]:
misc.face()

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ..., 
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ..., 
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ..., 
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ..., 
       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ..., 
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ..., 
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ..., 
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,

In [7]:
file_path = 'D:\Data\ORLDB'

In [10]:
im1 = misc.imread(os.path.join(file_path,'orl0101.bmp'),flatten=0)

In [9]:
import os

In [11]:
im1

array([[52, 46, 45, ..., 51, 52, 51],
       [46, 47, 47, ..., 31, 43, 51],
       [45, 51, 35, ..., 33, 43, 53],
       ..., 
       [47, 47, 50, ..., 42, 41, 49],
       [48, 46, 47, ..., 46, 45, 46],
       [51, 45, 50, ..., 42, 47, 46]], dtype=uint8)

In [12]:
names(im1)

NameError: name 'names' is not defined

AttributeError: type object 'list' has no attribute 'files'

In [14]:
os.listdir

<function nt.listdir>

In [15]:
os.listdir()

['.ipynb_checkpoints', 'lda.ipynb', 'lda1.py', 'Untitled.ipynb']

In [16]:
os.listdir(file_path)

['orl0101.bmp',
 'orl0102.bmp',
 'orl0103.bmp',
 'orl0104.bmp',
 'orl0105.bmp',
 'orl0106.bmp',
 'orl0107.bmp',
 'orl0108.bmp',
 'orl0109.bmp',
 'orl0110.bmp',
 'orl0201.bmp',
 'orl0202.bmp',
 'orl0203.bmp',
 'orl0204.bmp',
 'orl0205.bmp',
 'orl0206.bmp',
 'orl0207.bmp',
 'orl0208.bmp',
 'orl0209.bmp',
 'orl0210.bmp',
 'orl0301.bmp',
 'orl0302.bmp',
 'orl0303.bmp',
 'orl0304.bmp',
 'orl0305.bmp',
 'orl0306.bmp',
 'orl0307.bmp',
 'orl0308.bmp',
 'orl0309.bmp',
 'orl0310.bmp',
 'orl0401.bmp',
 'orl0402.bmp',
 'orl0403.bmp',
 'orl0404.bmp',
 'orl0405.bmp',
 'orl0406.bmp',
 'orl0407.bmp',
 'orl0408.bmp',
 'orl0409.bmp',
 'orl0410.bmp',
 'orl0501.bmp',
 'orl0502.bmp',
 'orl0503.bmp',
 'orl0504.bmp',
 'orl0505.bmp',
 'orl0506.bmp',
 'orl0507.bmp',
 'orl0508.bmp',
 'orl0509.bmp',
 'orl0510.bmp',
 'orl0601.bmp',
 'orl0602.bmp',
 'orl0603.bmp',
 'orl0604.bmp',
 'orl0605.bmp',
 'orl0606.bmp',
 'orl0607.bmp',
 'orl0608.bmp',
 'orl0609.bmp',
 'orl0610.bmp',
 'orl0701.bmp',
 'orl0702.bmp',
 'orl070

In [17]:
file_list.endswith

NameError: name 'file_list' is not defined

In [18]:
file_list = os.listdir(file_path)

In [19]:
file_list.endswith

AttributeError: 'list' object has no attribute 'endswith'

In [20]:
 file_list = [s for s in file_list if ".bmp" in s]

In [21]:
a = array

NameError: name 'array' is not defined

In [22]:
a = array()

NameError: name 'array' is not defined

In [25]:
a = np.array()

TypeError: Required argument 'object' (pos 1) not found

In [26]:
for file in file_list:
    image_read = misc.imread(os.path.join(file_path,file),flatten=TRUE)


NameError: name 'TRUE' is not defined

In [27]:
for file in file_list:
    image_read = misc.imread(os.path.join(file_path,file),flatten=True)

In [28]:
image_read

array([[ 125.,  125.,  123., ...,  116.,  118.,  115.],
       [ 126.,  125.,  123., ...,  121.,  117.,  113.],
       [ 128.,  126.,  124., ...,  116.,  116.,  118.],
       ..., 
       [  94.,   91.,   91., ...,   32.,   33.,   33.],
       [  91.,   94.,   91., ...,   32.,   32.,   35.],
       [  89.,   92.,   93., ...,   27.,   36.,   34.]], dtype=float32)

In [29]:
file

'orl4010.bmp'

In [30]:
file

'orl4010.bmp'

In [31]:
import re

In [38]:
re.findall('\d\d',file)

['40', '10']

In [39]:
[person,person_num] = re.findall('\d\d',file)

In [40]:
person

'40'

In [41]:
person_num

'10'

In [46]:
data_columns = ['data','person','person_num']

In [43]:
image_data

Empty DataFrame
Columns: []
Index: []

In [48]:
image_data = pd.DataFrame(columns=data_columns)

In [49]:
image_data

Empty DataFrame
Columns: [data, person, person_num]
Index: []

In [50]:
image_data = pd.DataFrame(columns = ['data','person','person_num'])

In [51]:
a = [image_data,person,person_num]

In [52]:
image_data.append(a,)

TypeError: cannot concatenate a non-NDFrame object

In [54]:
type(a)

list

In [55]:
data_read = {'data'=image_read,'person'=person,'person_num'=person_num}

SyntaxError: invalid syntax (<ipython-input-55-b2403ac151c4>, line 1)

In [56]:
data_read = {'data':image_read,'person':person,'person_num':person_num}

In [57]:
data_read

{'data': array([[ 125.,  125.,  123., ...,  116.,  118.,  115.],
        [ 126.,  125.,  123., ...,  121.,  117.,  113.],
        [ 128.,  126.,  124., ...,  116.,  116.,  118.],
        ..., 
        [  94.,   91.,   91., ...,   32.,   33.,   33.],
        [  91.,   94.,   91., ...,   32.,   32.,   35.],
        [  89.,   92.,   93., ...,   27.,   36.,   34.]], dtype=float32),
 'person': '40',
 'person_num': '10'}

In [62]:
image_data.append(data_read,ignore_index=True)

data person person_num
0  [[125.0, 125.0, 123.0, 122.0, 122.0, 123.0, 12...     40         10

In [60]:

for file in file_list:
    image_read = misc.imread(os.path.join(file_path,file),flatten=True)
    [person,person_num] = re.findall('\d\d',file)

    data_read = {'data':image_read,'person':person,'person_num':person_num}

    image_data.append(data_read,ignore_index=True)

In [61]:
image_data

Empty DataFrame
Columns: [data, person, person_num]
Index: []

In [63]:
for file in file_list:
    image_read = misc.imread(os.path.join(file_path,file),flatten=True)
    [person,person_num] = re.findall('\d\d',file)

    data_read = {'data':image_read,'person':person,'person_num':person_num}

    image_data.append(data_read,ignore_index=True)
    

In [64]:
image_data

Empty DataFrame
Columns: [data, person, person_num]
Index: []

In [65]:
image_data.append(data_read,ignore_index=True)

data person person_num
0  [[125.0, 125.0, 123.0, 122.0, 122.0, 123.0, 12...     40         10

In [66]:
file

'orl4010.bmp'

In [67]:
for file in file_list:
    image_read = misc.imread(os.path.join(file_path,file),flatten=True)
    [person,person_num] = re.findall('\d\d',file)

    data_read = {'data':image_read,'person':person,'person_num':person_num}

    image_data.append(data_read,ignore_index=True)
    
    print(file)


orl0101.bmp
orl0102.bmp
orl0103.bmp
orl0104.bmp
orl0105.bmp
orl0106.bmp
orl0107.bmp
orl0108.bmp
orl0109.bmp
orl0110.bmp
orl0201.bmp
orl0202.bmp
orl0203.bmp
orl0204.bmp
orl0205.bmp
orl0206.bmp
orl0207.bmp
orl0208.bmp
orl0209.bmp
orl0210.bmp
orl0301.bmp
orl0302.bmp
orl0303.bmp
orl0304.bmp
orl0305.bmp
orl0306.bmp
orl0307.bmp
orl0308.bmp
orl0309.bmp
orl0310.bmp
orl0401.bmp
orl0402.bmp
orl0403.bmp
orl0404.bmp
orl0405.bmp
orl0406.bmp
orl0407.bmp
orl0408.bmp
orl0409.bmp
orl0410.bmp
orl0501.bmp
orl0502.bmp
orl0503.bmp
orl0504.bmp
orl0505.bmp
orl0506.bmp
orl0507.bmp
orl0508.bmp
orl0509.bmp
orl0510.bmp
orl0601.bmp
orl0602.bmp
orl0603.bmp
orl0604.bmp
orl0605.bmp
orl0606.bmp
orl0607.bmp
orl0608.bmp
orl0609.bmp
orl0610.bmp
orl0701.bmp
orl0702.bmp
orl0703.bmp
orl0704.bmp
orl0705.bmp
orl0706.bmp
orl0707.bmp
orl0708.bmp
orl0709.bmp
orl0710.bmp
orl0801.bmp
orl0802.bmp
orl0803.bmp
orl0804.bmp
orl0805.bmp
orl0806.bmp
orl0807.bmp
orl0808.bmp
orl0809.bmp
orl0810.bmp
orl0901.bmp
orl0902.bmp
orl0903.bmp
orl0

In [68]:
image_data

Empty DataFrame
Columns: [data, person, person_num]
Index: []

In [69]:
for file in file_list:
    image_read = misc.imread(os.path.join(file_path,file),flatten=True)
    [person,person_num] = re.findall('\d\d',file)

    data_read = {'data':image_read,'person':person,'person_num':person_num}

    image_data = image_data.append(data_read,ignore_index=True)

In [70]:
image_data

data person person_num
0    [[52.0, 46.0, 45.0, 47.0, 40.0, 50.0, 69.0, 67...     01         01
1    [[73.0, 63.0, 69.0, 61.0, 69.0, 85.0, 91.0, 86...     01         02
2    [[44.0, 51.0, 50.0, 43.0, 40.0, 53.0, 76.0, 87...     01         03
3    [[48.0, 41.0, 29.0, 34.0, 46.0, 63.0, 75.0, 91...     01         04
4    [[61.0, 58.0, 78.0, 69.0, 62.0, 48.0, 47.0, 46...     01         05
5    [[53.0, 62.0, 67.0, 52.0, 77.0, 83.0, 84.0, 56...     01         06
6    [[43.0, 43.0, 46.0, 35.0, 49.0, 66.0, 48.0, 88...     01         07
7    [[38.0, 29.0, 36.0, 33.0, 57.0, 42.0, 36.0, 32...     01         08
8    [[41.0, 42.0, 34.0, 35.0, 47.0, 63.0, 45.0, 37...     01         09
9    [[30.0, 37.0, 38.0, 40.0, 55.0, 57.0, 72.0, 64...     01         10
10   [[35.0, 38.0, 32.0, 39.0, 35.0, 35.0, 37.0, 39...     02         01
11   [[36.0, 37.0, 37.0, 40.0, 38.0, 36.0, 38.0, 39...     02         02
12   [[38.0, 35.0, 33.0, 35.0, 35.0, 34.0, 36.0, 35...     02         03
13   [[34.0, 38.0, 38.0, 36.0, 38.0, 37.0, 33.0, 37...     02         04
14   [[30.0, 34.0, 35.0, 35.0, 37.0, 35.0, 33.0, 40...     02         05
15   [[35.0, 41.0, 38.0, 38.0, 35.0, 36.0, 38.0, 37...     02         06
16   [[39.0, 38.0, 38.0, 37.0, 39.0, 40.0, 37.0, 38...     02         07
17   [[35.0, 39.0, 37.0, 37.0, 40.0, 40.0, 39.0, 40...     02         08
18   [[39.0, 35.0, 37.0, 39.0, 39.0, 40.0, 41.0, 37...     02         09
19   [[39.0, 36.0, 35.0, 36.0, 39.0, 39.0, 37.0, 38...     02         10
20   [[106.0, 104.0, 103.0, 107.0, 106.0, 110.0, 11...     03         01
21   [[100.0, 102.0, 98.0, 101.0, 103.0, 108.0, 106...     03         02
22   [[104.0, 106.0, 104.0, 108.0, 106.0, 108.0, 10...     03         03
23   [[103.0, 104.0, 104.0, 107.0, 108.0, 107.0, 10...     03         04
24   [[101.0, 100.0, 105.0, 103.0, 104.0, 103.0, 10...     03         05
25   [[107.0, 110.0, 110.0, 107.0, 108.0, 106.0, 10...     03         06
26   [[106.0, 109.0, 108.0, 109.0, 113.0, 112.0, 11...     03         07
27   [[106.0, 105.0, 107.0, 107.0, 108.0, 111.0, 10...     03         08
28   [[108.0, 108.0, 109.0, 109.0, 108.0, 112.0, 11...     03         09
29   [[106.0, 107.0, 108.0, 107.0, 111.0, 112.0, 11...     03         10
..                                                 ...    ...        ...
370  [[112.0, 111.0, 112.0, 114.0, 114.0, 111.0, 11...     38         01
371  [[106.0, 108.0, 102.0, 107.0, 103.0, 108.0, 10...     38         02
372  [[109.0, 107.0, 101.0, 109.0, 108.0, 104.0, 10...     38         03
373  [[112.0, 110.0, 108.0, 112.0, 112.0, 109.0, 11...     38         04
374  [[102.0, 103.0, 105.0, 107.0, 103.0, 105.0, 10...     38         05
375  [[115.0, 112.0, 111.0, 110.0, 110.0, 112.0, 11...     38         06
376  [[106.0, 106.0, 103.0, 104.0, 107.0, 105.0, 10...     38         07
377  [[111.0, 110.0, 110.0, 112.0, 111.0, 110.0, 10...     38         08
378  [[111.0, 112.0, 112.0, 116.0, 113.0, 111.0, 11...     38         09
379  [[102.0, 103.0, 105.0, 107.0, 104.0, 104.0, 10...     38         10
380  [[84.0, 86.0, 84.0, 86.0, 60.0, 41.0, 44.0, 57...     39         01
381  [[74.0, 75.0, 75.0, 79.0, 59.0, 41.0, 40.0, 46...     39         02
382  [[75.0, 77.0, 76.0, 78.0, 56.0, 45.0, 36.0, 57...     39         03
383  [[76.0, 72.0, 67.0, 56.0, 62.0, 60.0, 41.0, 45...     39         04
384  [[91.0, 89.0, 89.0, 90.0, 88.0, 88.0, 92.0, 92...     39         05
385  [[92.0, 92.0, 91.0, 90.0, 91.0, 90.0, 81.0, 82...     39         06
386  [[89.0, 89.0, 84.0, 91.0, 92.0, 90.0, 88.0, 87...     39         07
387  [[88.0, 86.0, 87.0, 90.0, 94.0, 89.0, 93.0, 89...     39         08
388  [[88.0, 89.0, 85.0, 91.0, 88.0, 88.0, 90.0, 90...     39         09
389  [[87.0, 90.0, 86.0, 88.0, 87.0, 87.0, 98.0, 78...     39         10
390  [[123.0, 124.0, 125.0, 121.0, 122.0, 121.0, 12...     40         01
391  [[126.0, 132.0, 129.0, 127.0, 126.0, 126.0, 12...     40         02
392  [[128.0, 128.0, 124.0, 128.0, 126.0, 123.0, 12...     40         03
393  [[130.0, 126.0, 123.0, 125.0, 

In [71]:

for file in file_list:
    image_read = misc.imread(os.path.join(file_path,file),flatten=True)
    [person,person_num] = re.findall('\d\d',file)

    data_read = {'data':image_read,'person':person,'person_num':person_num}

    image_data = pd.concat([image_data,data_read],ignore_index=True)
    

TypeError: cannot concatenate a non-NDFrame object

In [72]:
a = pd.concat([image_data,data_read],ignore_index=True)

TypeError: cannot concatenate a non-NDFrame object