In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage
#from lr_utils import load_dataset
import lr_utils
%matplotlib inline

In [ ]:
import h5py
    
    
def load_dataset():
    train_dataset = h5py.File('datasets/train_catvnoncat.h5', "r")
    train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
    train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

    test_dataset = h5py.File('datasets/test_catvnoncat.h5', "r")
    test_set_x_orig = np.array(test_dataset["test_set_x"][:]) # your test set features
    test_set_y_orig = np.array(test_dataset["test_set_y"][:]) # your test set labels

    classes = np.array(test_dataset["list_classes"][:]) # the list of classes
    
    train_set_y_orig = train_set_y_orig.reshape((1, train_set_y_orig.shape[0]))
    test_set_y_orig = test_set_y_orig.reshape((1, test_set_y_orig.shape[0]))
    
    return train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes

In [ ]:
!python -m pip install --upgrade pip

In [ ]:
!pip install msgpack

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage
#from lr_utils import load_dataset

%matplotlib inline

#lr_utils.py
import h5py
    
    
def load_dataset():
    train_dataset = h5py.File('D:\\Matlab_Drive\\Data\\Study_1stsummer\\datasets\\train_catvnoncat.h5', "r")
    train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
    train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

    test_dataset = h5py.File('D:\\Matlab_Drive\\Data\\Study_1stsummer\\datasets\\test_catvnoncat.h5', "r")
    test_set_x_orig = np.array(test_dataset["test_set_x"][:]) # your test set features
    test_set_y_orig = np.array(test_dataset["test_set_y"][:]) # your test set labels

    classes = np.array(test_dataset["list_classes"][:]) # the list of classes
    
    train_set_y_orig = train_set_y_orig.reshape((1, train_set_y_orig.shape[0]))
    test_set_y_orig = test_set_y_orig.reshape((1, test_set_y_orig.shape[0]))
    
    return train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes

# Loading the data (cat/non-cat)
train_set_x_orig, train_set_y, test_set_x_orig, test_set_y, classes = load_dataset()

In [ ]:
train_set_x_orig.shape

In [ ]:
# Example of a picture
index = 1
plt.imshow(train_set_x_orig[index])
print ("y = " + str(train_set_y[:, index]) + ", it's a '" + classes[np.squeeze(train_set_y[:, index])].decode("utf-8") +  "' picture.")

In [ ]:
aa = train_set_x_orig.reshape()

In [ ]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1)

In [ ]:
train_set_x_orig.shape

In [ ]:
aa.shape

In [ ]:
aa[0]

In [ ]:
train_set_y.shape

In [ ]:
X.shape

In [ ]:
w = np.random.normal([1,12288])

In [ ]:
w

In [ ]:
w = np.random.rand(X.shape[0],1)

In [ ]:
w.shape

In [ ]:
a = np.dot(w,X.T)

In [ ]:
a.shape

In [ ]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T

In [ ]:
X.shape

In [ ]:
a = np.dot(w.T,X)

In [ ]:
b = np.random.rand(1,X.shape[1])

In [ ]:
b.shape

In [ ]:
a.shape

In [ ]:
Z = np.dot(w.T,X)+b

In [ ]:
import math

In [ ]:
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [ ]:
A = sigmoid(Z)

In [ ]:
xx = X[:,0]

In [ ]:
ww = w[:,0]

In [ ]:
bb = b[0]

In [ ]:
zz = np.dot(ww.T,xx)+bb

In [ ]:
xx.shape

In [ ]:
zz.shape

In [ ]:
aa = sigmoid(zz)

In [ ]:
yy=train_set_y[:,0]

In [ ]:
yy

In [ ]:
dz = aa-yy

In [ ]:
dz

In [ ]:
aa

In [ ]:
yy[0]

In [ ]:
dz = aa-yy[0]

In [ ]:
m = train_set_x_orig.shape[0]

In [ ]:
m

In [ ]:
dw = (1/m)*xx*dz.T

In [ ]:
xx.shape

In [ ]:
db = (1/m)*np.sum(dz)

In [ ]:
alpha = 0.01

In [ ]:
w.shape

In [ ]:
ww

In [ ]:
ww.shape

In [ ]:
zz = np.dot(w.T,xx)+b

In [ ]:
Z = np.dot(w.T,xx)+b
A = sigmoid(Z)

In [ ]:
Z.shape

In [ ]:
Z.shape

In [ ]:
w.shape

In [ ]:
b.shape

In [ ]:
b = np.random.rand(1)

In [ ]:
b

In [ ]:
Z = np.dot(w.T,xx)+b

In [ ]:
Z.shape

In [ ]:
A = sigmoid(Z)

In [ ]:
yy=train_set_y[:,0]

In [ ]:
dz = A-yy[0]

In [ ]:
dw = (1/m)*xx*dz.T
db = (1/m)*np.sum(dz)

In [ ]:
w = w - alpha*dw
b = b - alpha*db

In [ ]:
X.shape,train_set_y.shape

In [ ]:
len(train_set_y)

In [ ]:
for i in range(X.shape[1]):
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy[0]
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

In [ ]:
A.shape

In [ ]:
i

In [ ]:
i = 0

In [ ]:
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]


In [ ]:
Z.shape

In [ ]:
xx.shape

In [ ]:
X[:,0].shape

In [ ]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1,X.shape[1])
b = np.random.rand(1)


In [ ]:
for i in range(X.shape[1]):
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy[0]
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

In [ ]:
np.dot(w.T,xx).shape

In [ ]:
w.shape

In [ ]:
w = np.random.rand(X.shape[1],1)

In [ ]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1,X.shape[1])
b = np.random.rand(1)

In [ ]:
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b

In [ ]:
Z.shape

In [ ]:
A = sigmoid(Z)

In [ ]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1,X.shape[1])
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy[0]
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

In [ ]:
Z.shape

In [ ]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1,X.shape[1])
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [ ]:
w.shape

In [ ]:
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

In [ ]:
w = w - alpha*dw

In [ ]:
w.shape

In [ ]:
dz.shape

In [ ]:
dz = A-yy

In [ ]:
dz.shape

In [ ]:
dw = (1/m)*xx*dz.T

In [ ]:
dw.shape

In [ ]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1,X.shape[1])
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

In [ ]:
dw.shape

In [ ]:
w.shape

In [ ]:
w = np.random.rand(X.shape[0],1)

In [ ]:
w.shape

In [ ]:
dd = A-yy

In [ ]:
dd.shape

In [ ]:
dd.T

In [ ]:
xx.shape

In [ ]:
w.T.shape

In [ ]:
xx.shape

In [ ]:
np.dot(w.T,xx).shape

In [ ]:
b.shape

In [ ]:
Z = np.dot(w.T,xx)+b

In [ ]:
Z.shape

In [ ]:
A = sigmoid(Z)

In [ ]:
A

In [ ]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1,X.shape[1])
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [ ]:
i = 0

In [ ]:
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

In [ ]:
i = 1

In [ ]:
w.shape

In [ ]:
dw.shape

In [ ]:
w = np.random.rand(X.shape[0],1)

In [ ]:
w.shape

In [ ]:
(w - dw).shape

In [ ]:
dz.shape

In [ ]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1,X.shape[1])
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy
    dw = (1/m)*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

In [ ]:
X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1)

In [ ]:
X_test.shape

In [ ]:
w.shape

In [ ]:
y_hat = np.dot(w,X_test)+b

In [ ]:
w.T.shape

In [ ]:
X_test.shape

In [ ]:
X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T

In [ ]:
y_hat = np.dot(w.T,X_test)+b

In [ ]:
y_hat.shape

In [ ]:
np.unique(y_hat)

In [ ]:
y_hat.shape

In [ ]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy
    dw = (1/m)*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

In [ ]:
w

In [ ]:
X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T
y_hat = np.dot(w.T,X_test)+b

In [ ]:
y_hat

In [ ]:
dw

In [ ]:
w

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage
#from lr_utils import load_dataset

%matplotlib inline

#lr_utils.py
import h5py
    
    
def load_dataset():
    train_dataset = h5py.File('D:\\Matlab_Drive\\Data\\Study_1stsummer\\datasets\\train_catvnoncat.h5', "r")
    train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
    train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

    test_dataset = h5py.File('D:\\Matlab_Drive\\Data\\Study_1stsummer\\datasets\\test_catvnoncat.h5', "r")
    test_set_x_orig = np.array(test_dataset["test_set_x"][:]) # your test set features
    test_set_y_orig = np.array(test_dataset["test_set_y"][:]) # your test set labels

    classes = np.array(test_dataset["list_classes"][:]) # the list of classes
    
    train_set_y_orig = train_set_y_orig.reshape((1, train_set_y_orig.shape[0]))
    test_set_y_orig = test_set_y_orig.reshape((1, test_set_y_orig.shape[0]))
    
    return train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes

# Loading the data (cat/non-cat)
train_set_x_orig, train_set_y, test_set_x_orig, test_set_y, classes = load_dataset()

# linear reg

X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy
    dw = (1/m)*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

# test

X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T
y_hat = np.dot(w.T,X_test)+b

C:\Users\herok\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
y_hat.shape

(1, 50)

In [7]:
w

array([[0.90893708],
       [0.37554054],
       [0.66481326],
       ...,
       [0.80414551],
       [0.25061182],
       [0.97968814]])

In [8]:
w.T.shape

(1, 12288)

In [9]:
X_test.shape

(12288, 50)

In [10]:
b.shape

(1,)

In [11]:
b

array([0.14119888])

In [12]:
db

0.004784688995215311

In [13]:
dw.shape

(1,)

In [14]:
dw

array([0.00478469])

In [19]:
a = (1/m)*xx*dz.T

In [20]:
a.shape

(12288,)

In [21]:
a

array([0.03827751, 0.13397129, 0.25358852, ..., 0.        , 0.        ,
       0.        ])

In [22]:
len(a)

12288

In [23]:
len(dw)

1

In [24]:
len(w)

12288

In [25]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db


TypeError: only size-1 arrays can be converted to Python scalars

In [26]:
i

1

In [27]:
dw

array([0.08133971, 0.14832536, 0.26794258, ..., 0.        , 0.        ,
       0.        ])

In [28]:
dw.shape

(12288,)

In [29]:
w.shape

(12288, 12288)

In [30]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

In [31]:
w.shape

(12288, 1)

In [32]:
w = np.random.rand(X.shape[0])

In [33]:
w.shape

(12288,)

In [34]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0])
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i]
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db


OverflowError: math range error

In [35]:
dw

array([0., 0., 0., ..., 0., 0., 0.])

In [36]:
w

array([-0.04205502, -0.41844867,  0.50337286, ...,  0.24459135,
        0.1184121 ,  0.40072357])

In [37]:
i

157

In [38]:
X.shape

(12288, 209)

In [39]:
Z

array([-20941.84979381])

In [40]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0])
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

In [41]:
w.T.shape

(12288,)

In [42]:
xx.shape

(12288,)

In [43]:
w.shape

(12288,)

In [44]:
xx.shape

(12288,)

In [45]:
type(xx)

numpy.ndarray

In [46]:
X.shape

(12288, 209)

In [47]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

In [48]:
w.shape

(12288, 1)

In [52]:
xx.shape

(12288, 1)

In [53]:
for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i]

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

OverflowError: math range error

In [54]:
Z

array([[-19246.53124678]])

In [55]:
b

array([0.24383031])

In [57]:
np.dot(w.T,xx).shape

(1, 1)

In [58]:
A.shape

AttributeError: 'float' object has no attribute 'shape'

In [59]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

OverflowError: math range error

In [60]:
A

1.0

In [61]:
Z

array([[-1071.93035274]])

In [63]:
Z

array([[-1071.93035274]])

In [65]:
sigmoid(Z[0][0])

OverflowError: math range error

In [66]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [67]:
i = 0

In [68]:
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

In [69]:
A

1.0

In [70]:
Z

array([[417677.92673364]])

In [72]:
w.T.shape

(1, 12288)

In [73]:
xx.shape

(12288, 1)

In [75]:
xx

array([[17],
       [31],
       [56],
       ...,
       [ 0],
       [ 0],
       [ 0]], dtype=uint8)

In [76]:

X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = np.random.rand(X.shape[0],1)
b = np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.0001
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

In [77]:
X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T
y_hat = np.dot(w.T,X_test)+b

In [79]:
w

array([[0.06199129],
       [0.39721246],
       [0.15219858],
       ...,
       [0.77190004],
       [0.71948257],
       [0.54185864]])

In [80]:
b

array([0.96047101])

In [81]:
X_test

array([[158, 115, 255, ...,  41,  18, 133],
       [104, 110, 253, ...,  47,  18, 163],
       [ 83, 111, 254, ...,  84,  16,  75],
       ...,
       [173, 171, 133, ..., 183, 144,   5],
       [128, 176, 101, ..., 141, 137,  22],
       [110, 186, 121, ..., 116, 108,   5]], dtype=uint8)

In [82]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
w = 0.01 * np.random.rand(X.shape[0],1)
b = 0.01 * np.random.rand(1)

m = train_set_x_orig.shape[0]
alpha = 0.0001
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

# test

X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T
y_hat = np.dot(w.T,X_test)+b

In [83]:
y_hat

array([[-111.69369819,   84.24073543, -136.80031913, -154.90576897,
        -164.85990972,   -2.72064262, -180.79797564,    3.76537172,
         -63.26226797,  -77.68360241,  -68.31278872, -167.41807481,
          -5.75007867,   62.74555974, -207.56127709, -106.67785696,
        -158.39987539, -178.31043838, -418.17131825, -298.82707312,
        -125.70955329, -225.62241145, -188.10330079, -114.77504308,
         -30.65247661, -152.33525864, -240.78564912, -161.082861  ,
         -71.95519351, -266.76284702,  -46.04247869, -107.23048944,
        -147.25713467,  -84.91301837, -100.04976519, -336.62787069,
        -122.54992604,  -69.51242224,  -49.02445585, -268.6060647 ,
        -246.06348161,   91.43349217,  -79.24846124, -242.34759593,
          43.5713877 , -140.98099663, -156.20886491,   11.11255314,
         -43.84271141, -191.36347325]])

In [87]:
np.zeros((X.shape[0],1))

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [88]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
#w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1)
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.0001
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

In [89]:
X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T
y_hat = np.dot(w.T,X_test)+b


In [90]:
y_hat

array([[-16.79211665, -19.55034897, -27.33776592, -10.030996  ,
        -34.68497635, -19.00754079, -37.04147185, -12.12810426,
        -22.36635253,  -1.92810818, -37.46706356, -20.56577399,
        -19.96444644,  -4.6276895 , -29.68314277, -10.82459736,
        -31.6501523 , -25.61293102, -32.35164518, -33.65521436,
        -32.98203526, -31.57765733, -33.03414744, -31.4460218 ,
         -9.33390631,  -0.47126589, -33.93442476, -37.08644455,
        -17.76266878, -11.61712094, -36.38475318, -20.36514929,
        -33.02125707, -14.756824  , -27.39271398, -46.16597732,
        -35.9824477 , -18.0863183 , -15.16016304, -42.19892814,
         -6.54151022, -10.79782487, -34.24355148, -27.97585808,
         -6.65436438, -20.99912572, -27.84253123,  15.92467777,
        -31.18565014, -43.30471025]])

In [91]:
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.1
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

# test

X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T
y_hat = np.dot(w.T,X_test)+b


OverflowError: math range error

In [95]:
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.001
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

# test

X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T
y_hat = np.dot(w.T,X_test)+b


OverflowError: math range error

In [94]:
dw.shape

(12288, 1)

In [96]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T/255
#w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1)
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.001
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

# test

X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T/255
y_hat = np.dot(w.T,X_test)+b

In [97]:
y_hat

array([[-0.2256161 , -0.3317652 , -0.35140613, -0.25742261, -0.38064079,
        -0.16373387, -0.39191187, -0.24356573, -0.26539711, -0.22120046,
        -0.19396633, -0.28221411, -0.14960097, -0.33014015, -0.18382739,
        -0.19955056, -0.1723709 , -0.29620597, -0.21430748, -0.257651  ,
        -0.25246227, -0.16869822, -0.20238053, -0.22691483, -0.18107615,
        -0.17203459, -0.28391485, -0.19883125, -0.18578691, -0.18793071,
        -0.16306326, -0.25660394, -0.29838983, -0.27536781, -0.21562149,
        -0.26369887, -0.23180218, -0.26968701, -0.23760169, -0.14758075,
        -0.16225858, -0.25823893, -0.25566424, -0.12301334, -0.16662809,
        -0.20194665, -0.23998456, -0.23604367, -0.21367339, -0.24033105]])

In [98]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T/255
#w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1)
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.1
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

# test

X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T/255
y_hat = np.dot(w.T,X_test)+b

In [99]:
y_hat

array([[-1.80044403, -2.52192033, -2.78366899, -2.03713011, -3.38366465,
        -1.44366105, -3.21474736, -1.96488426, -2.21015362, -1.53763238,
        -2.08716236, -2.10666165, -1.396465  , -2.01237984, -2.05999218,
        -1.7709642 , -1.89396969, -2.40574586, -2.27124826, -2.61161043,
        -2.15579579, -1.79733861, -2.19158774, -1.84047702, -1.38034862,
        -1.26839936, -2.60300275, -1.93620379, -1.48358208, -1.53685163,
        -1.83681852, -2.37430336, -2.95080813, -2.10144802, -1.84117125,
        -2.63156139, -2.35287276, -2.14885907, -1.89524457, -1.88668323,
        -1.35177513, -1.96201828, -2.36836139, -1.50854156, -1.39972306,
        -1.89313481, -2.15240537, -1.28574106, -1.90442527, -2.44187202]])

In [100]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T/255
w = np.random.rand(X.shape[0],1)
b = np.random.rand(1)
#w = np.zeros((X.shape[0],1))
#b = 0

m = train_set_x_orig.shape[0]
alpha = 0.1
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*xx*dz.T
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

# test

X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T/255
y_hat = np.dot(w.T,X_test)+b


In [101]:
y_hat

array([[2407.36198365, 3724.40706873, 3803.43405702, 2742.79476963,
        4070.41093281, 1784.7533501 , 4195.52270645, 2673.35242118,
        2888.27791957, 2406.17068037, 2069.59684181, 3029.62797974,
        1636.77441766, 3695.74258282, 1839.86272255, 2138.97381505,
        1777.77486762, 3152.13184209, 2075.10083974, 2624.80315864,
        2734.33640922, 1691.05108035, 2049.44318171, 2435.31804723,
        1990.17353583, 1842.09482377, 2988.17469606, 2083.41802908,
        2001.51178427, 1905.68538504, 1733.68747034, 2746.02434324,
        3157.51712548, 2984.10439776, 2318.5190864 , 2667.37537573,
        2441.75617032, 2960.08872603, 2586.09038374, 1449.81026191,
        1644.08349358, 2910.79079664, 2754.80016595, 1187.33158672,
        1849.46667769, 2124.7208288 , 2539.89030662, 2650.78928641,
        2328.44278279, 2495.99686883]])

In [102]:
1/m

0.004784688995215311

In [103]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T/255
#w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1)
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.1
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*np.dot(xx*dz.T)
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

# test

X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T/255
y_hat = np.dot(w.T,X_test)+b


TypeError: Required argument 'b' (pos 2) not found

In [104]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T/255
#w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1)
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.1
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)

    dz = A-yy
    dw = (1/m)*np.dot(xx,dz.T)
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db

# test

X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T/255
y_hat = np.dot(w.T,X_test)+b

In [105]:
y_hat

array([[-1.80044403, -2.52192033, -2.78366899, -2.03713011, -3.38366465,
        -1.44366105, -3.21474736, -1.96488426, -2.21015362, -1.53763238,
        -2.08716236, -2.10666165, -1.396465  , -2.01237984, -2.05999218,
        -1.7709642 , -1.89396969, -2.40574586, -2.27124826, -2.61161043,
        -2.15579579, -1.79733861, -2.19158774, -1.84047702, -1.38034862,
        -1.26839936, -2.60300275, -1.93620379, -1.48358208, -1.53685163,
        -1.83681852, -2.37430336, -2.95080813, -2.10144802, -1.84117125,
        -2.63156139, -2.35287276, -2.14885907, -1.89524457, -1.88668323,
        -1.35177513, -1.96201828, -2.36836139, -1.50854156, -1.39972306,
        -1.89313481, -2.15240537, -1.28574106, -1.90442527, -2.44187202]])

In [112]:
sigmoid(y_hat[0][20])

0.10379086884426905

In [116]:
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.1
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    xx = X[:,i].reshape(-1,1)
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    yy=train_set_y[:,i].reshape(-1,1)
    cost = -1/m*np.sum(yy*np.log(A)+(1-yy)*np.log(1-A)) 

    dz = A-yy
    dw = (1/m)*np.dot(xx,dz.T)
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db
    print(cost)

0.0033164936868896903
0.002481638912983133
0.006123938798085221
0.003464448509479687
0.0029089023886756287
0.0027425730700556283
0.002261151508281698
0.005277712149232269
0.0024706204742601665
0.0019430713466872794
0.0010458219296767032
0.007085833704922531
0.0023829821840002327
0.0068845017661157155
0.0029491163503585494
0.006191222736091625
0.0018406758328731333
0.0009457867683572831
0.0014170121469038975
0.0046213098462161385
0.00174740310117924
0.0019370787023508715
0.00042316772115383235
0.0003960338317400988
0.010076858280765797
0.00381228909608764
0.0023598115700659197
0.0042206448902209846
0.0034566845199633664
0.005842889846298512
0.0035495923636692977
0.003154411514617951
0.0008819202760508344
0.001590249982910682
0.0017517110560804018
0.0015754680401737116
0.001151344446669914
0.00030423910010942155
0.004488978902085086
0.0010407191991963227
0.0004060811628665773
0.005602899061976305
0.012051869619285262
0.0013487905271098281
0.0014134727455008382
0.0018840338225310897
0.000

In [117]:
m

209

In [118]:
X.shape

(12288, 209)

In [119]:
w = np.zeros((X.shape[0],1))

In [120]:
w.shape

(12288, 1)

In [121]:
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.1
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))


for i in range(X.shape[1]):
    #xx = X[:,i].reshape(-1,1)
    xx=X
    yy=train_set_y
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    #yy=train_set_y[:,i].reshape(-1,1)
    cost = -1/m*np.sum(yy*np.log(A)+(1-yy)*np.log(1-A)) 

    dz = A-yy
    dw = (1/m)*np.dot(xx,dz.T)
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db
    print(cost)

TypeError: only size-1 arrays can be converted to Python scalars

In [122]:
print ("sigmoid([0, 2]) = " + str(sigmoid(np.array([0,2]))))

TypeError: only size-1 arrays can be converted to Python scalars

In [123]:
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.1
import math

def sigmoid(x):
  return 1 / (1 + 1/np.exp(x))


for i in range(X.shape[1]):
    #xx = X[:,i].reshape(-1,1)
    xx=X
    yy=train_set_y
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    #yy=train_set_y[:,i].reshape(-1,1)
    cost = -1/m*np.sum(yy*np.log(A)+(1-yy)*np.log(1-A)) 

    dz = A-yy
    dw = (1/m)*np.dot(xx,dz.T)
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db
    print(cost)

0.6931471805599453
10.510880267262182
nan
31.53366888989145
6.1258347742089
nan
27.159120226304506
1.785823293501695
nan
24.242660082432945
1.2928489929664675
22.192845272911896
3.8928140432942695
38.091325471687476
12.682107645782176
nan
33.70229153653934
8.294774681025459
nan
29.328163089938815
3.9448226703689593
nan
25.430099806942565
1.1017310522851544
6.312373117010055
34.320527649254835
8.912852349874267
nan
29.888352154280877
4.517453891863581
nan
26.138269247798135
1.5439530984046914
nan
33.359880600515645
7.957303002196304
nan
28.744938867509173

C:\Users\herok\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in log
C:\Users\herok\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in multiply



3.557517501801692
nan
27.628988974612582
2.7005967833014406
nan
28.841812795918063
3.701565874469232
nan
27.639714191957832
2.799110050552795
nan
28.95497938162222
3.8563859856492306
nan
27.454956751266767
2.759741976048241
nan
28.49888799994843
3.540155283317106
nan
27.550512133840755
2.883291217300099
nan
27.797708212440938
3.0675188736432517
nan
27.507118680488666
2.8899591475009307
nan
27.018434538215292
2.5864356224326825
nan
26.399274368244797
2.215865021881455
nan
26.51221621929782
2.2373867316316476
nan
26.370529630074124
2.1389722873850086
nan
26.386327452245226
2.1300949707804055
nan
26.499579935480064
2.1877576972890336
nan
26.761379901931008
2.3544271742466596
nan
27.085119102038128
2.589084537768407
nan
26.880542176887428
2.4786666733207072
nan
26.070658908768593
2.015698449998031
nan
25.523103198250293
1.7425281563460115
nan
23.94082346005826
1.3108917002965044
1.630717856280536
6.767941692574218
nan
26.25097786111294
2.041477001072049
nan
26.011629201790264
1.9122794010

In [124]:
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.001
import math

def sigmoid(x):
  return 1 / (1 + 1/np.exp(x))


for i in range(X.shape[1]):
    #xx = X[:,i].reshape(-1,1)
    xx=X
    yy=train_set_y
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    #yy=train_set_y[:,i].reshape(-1,1)
    cost = -1/m*np.sum(yy*np.log(A)+(1-yy)*np.log(1-A)) 

    dz = A-yy
    dw = (1/m)*np.dot(xx,dz.T)
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db
    print(cost)

0.6931471805599453
0.6602163017690019
0.6526585611009366
0.6502497388185607
0.6489887705026202
0.6480063806213199
0.647099811966631
0.6462198002970412
0.6453540182894317
0.644499232581576
0.6436544764306668
0.6428193536253203
0.6419936145289409
0.6411770498179609
0.6403694637979015
0.6395706676604929
0.6387804777293385
0.6379987149485814
0.6372252046793091
0.6364597765717578
0.6357022644565815
0.6349525062417116
0.6342103438117964
0.633475622929652
0.6327481931396676
0.6320279076731887
0.631314623355897
0.630608200517192
0.6299085029015656
0.6292153975819603
0.6285287548750871
0.627848448258686
0.6271743542907062
0.6265063525303773
0.6258443254611479
0.625188158415463
0.624537739501354
0.623892959530807
0.6232537119498838
0.6226198927705643
0.6219914005042768
0.621368136097089
0.6207500028665225
0.620136906439965
0.6195287546946441
0.6189254576991309
0.6183269276563446
0.6177330788480225
0.6171438275806259
0.6165590921326487
0.6159787927033
0.6154028513625254
0.6148311920023416
0.61426

In [125]:
#b = np.random.rand(1)
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.01
import math

def sigmoid(x):
  return 1 / (1 + 1/np.exp(x))


for i in range(X.shape[1]):
    #xx = X[:,i].reshape(-1,1)
    xx=X
    yy=train_set_y
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    #yy=train_set_y[:,i].reshape(-1,1)
    cost = -1/m*np.sum(yy*np.log(A)+(1-yy)*np.log(1-A)) 

    dz = A-yy
    dw = (1/m)*np.dot(xx,dz.T)
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db
    print(cost)

0.6931471805599453
1.1201739474561658
2.1127183805985696
3.1997290177984428
0.8100261060105536
1.8874109951783227
3.1881676760526965
0.7949783817423247
1.8706974174852222
3.1513560070049493
0.7648481658963865
1.802202325089909
3.113051478606343
0.7356117417067402
1.721601153821593
3.0698415680999123
0.7051661626075593
1.6227657065309702
3.0182244725746434
0.6719081806153118
1.4963431351303782
2.949022059586552
0.6323339800435082
1.3139214953075353
2.8283499427181233
0.5775558543072069
0.9667092700909913
2.416879702846525
0.5594224794650072
0.8473694424360794
1.8485074169447326
2.9149952446403513
0.6061398574888199
1.2364232001163353
2.696790061688035
0.5264808290812681
0.6582804224087041
1.5344517149021688
1.2992095821532126
2.7144409289813662
0.5234222868466308
0.7190704405345127
1.779447819616104
0.9748252434435181
2.3604361833631766
0.5209805965829541
0.7649435446899601
1.6727340564224509
2.7839076003426286
0.5362945103956834
0.9241854522216333
2.2459098104931354
0.5440577551137148


In [126]:
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.001
import math

def sigmoid(x):
  return 1 / (1 + 1/np.exp(x))


for i in range(X.shape[1]):
    #xx = X[:,i].reshape(-1,1)
    xx=X
    yy=train_set_y
    Z = np.dot(w.T,xx)+b
    A = sigmoid(Z)
    #yy=train_set_y[:,i].reshape(-1,1)
    cost = -1/m*np.sum(yy*np.log(A)+(1-yy)*np.log(1-A)) 

    dz = A-yy
    dw = (1/m)*np.dot(xx,dz.T)
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db
    print(cost)

0.6931471805599453
0.6602163017690019
0.6526585611009366
0.6502497388185607
0.6489887705026202
0.6480063806213199
0.647099811966631
0.6462198002970412
0.6453540182894317
0.644499232581576
0.6436544764306668
0.6428193536253203
0.6419936145289409
0.6411770498179609
0.6403694637979015
0.6395706676604929
0.6387804777293385
0.6379987149485814
0.6372252046793091
0.6364597765717578
0.6357022644565815
0.6349525062417116
0.6342103438117964
0.633475622929652
0.6327481931396676
0.6320279076731887
0.631314623355897
0.630608200517192
0.6299085029015656
0.6292153975819603
0.6285287548750871
0.627848448258686
0.6271743542907062
0.6265063525303773
0.6258443254611479
0.625188158415463
0.624537739501354
0.623892959530807
0.6232537119498838
0.6226198927705643
0.6219914005042768
0.621368136097089
0.6207500028665225
0.620136906439965
0.6195287546946441
0.6189254576991309
0.6183269276563446
0.6177330788480225
0.6171438275806259
0.6165590921326487
0.6159787927033
0.6154028513625254
0.6148311920023416
0.61426

In [127]:
X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T/255
y_hat = np.dot(w.T,X_test)+b

In [128]:
y_hat

array([[-0.08301109,  0.04160135, -0.23908267, -0.0908986 , -0.62675317,
        -0.24017894, -0.96110546, -0.02242462, -0.05290995, -0.11798891,
        -0.5191334 , -0.28866575, -0.1008618 ,  0.07794987, -1.01822355,
        -0.0825472 , -0.90359602, -0.43100859, -1.05481695, -1.01830311,
        -0.33481713, -1.01018527, -1.2903412 , -0.49978987,  0.13707787,
        -0.00494252, -0.56853279, -0.87845316, -0.4660683 , -0.02817919,
        -0.48205036, -0.43822903, -0.66476854, -0.45826279, -0.3185032 ,
        -1.30205075, -0.82875938, -0.10455555, -0.22459419, -1.1433068 ,
        -0.47745319,  0.08951992, -0.47728409, -0.88211415, -0.00638634,
        -0.78353125, -0.64054561,  0.61825749, -0.37319302, -0.96575948]])

In [129]:
X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T/255
y_hat = sigmoid(np.dot(w.T,X_test)+b)

In [130]:
y_hat

array([[0.47925914, 0.51039884, 0.44051242, 0.47729098, 0.34824711,
        0.44024225, 0.27665692, 0.49439408, 0.4867756 , 0.47053695,
        0.3730549 , 0.42833054, 0.47480591, 0.51947761, 0.26537358,
        0.47937491, 0.28831208, 0.39388552, 0.25830119, 0.26535807,
        0.417069  , 0.26694359, 0.21579506, 0.37759005, 0.53421591,
        0.49876437, 0.36157545, 0.29349842, 0.38554725, 0.49295567,
        0.38176808, 0.39216304, 0.33966924, 0.38739802, 0.42104057,
        0.21382008, 0.30390746, 0.4738849 , 0.44408629, 0.24171375,
        0.3828537 , 0.52236505, 0.38289365, 0.29273987, 0.49840342,
        0.31355932, 0.34512321, 0.64982214, 0.4077697 , 0.27572653]])

In [ ]:
X = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T/255
Y = train_set_y
#w = np.random.rand(X.shape[0],1)
#b = np.random.rand(1)
w = np.zeros((X.shape[0],1))
b = 0

m = train_set_x_orig.shape[0]
alpha = 0.01

def sigmoid(x):
  return 1 / (1 + 1/np.exp(x))

costs = []

for i in range(100):
    Z = np.dot(w.T,X)+b
    A = sigmoid(Z)
    cost = -1/m*np.sum(*np.log(A)+(1-Y)*np.log(1-A)) 

    dz = A-Y
    dw = (1/m)*np.dot(X,dz.T)
    db = (1/m)*np.sum(dz)

    w = w - alpha*dw
    b = b - alpha*db
    
    costs.append(cost)
# test

X_test = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T/255
y_hat = 1*(sigmoid(np.dot(w.T,X_test)+b) >= 0.5)


acc = 1 - np.sum(np.abs(y_hat - test_set_y)) / X_test.shape[1]
print(acc)