In [3]:
import scipy.io as sio
import os
import re
import numpy as np

# For Windows
file_path = 'D:\\Matlab_Drive\\Data\\WIFI\\csi_0629_1247'
file_list = os.listdir(file_path)

abs_csi = {}
for file in file_list:
    data_read = sio.loadmat(os.path.join(file_path,file))
    num_search = re.search('\d+',file)
    csi_num = num_search.group(0)
    abs_csi[csi_num] = np.abs(data_read['csi'])

In [4]:
list_abs = []
for i in range(len(abs_csi)):
    abs_val = abs_csi[str(i+1)]
    list_abs.append(abs_val)


In [6]:
len(list_abs)

30329

In [7]:
arr_abs = np.array(list_abs)

In [8]:
arr_abs.shape

(30329,)

In [10]:
arr_abs[0].shape

(2, 3, 30)

In [11]:
list_abs = []
for i in range(len(abs_csi)):
    abs_val = np.mean(abs_csi[str(i+1)],axis=2)
    list_abs.append(abs_val)


In [12]:
list_abs.shape

AttributeError: 'list' object has no attribute 'shape'

In [26]:
arr_abs = np.asarray(list_abs)

In [27]:
arr_abs.shape

(30329,)

In [28]:
arr_abs[0].shape

(2, 3)

In [30]:
arr_abs[0:1]

array([array([[ 0.60915119, 30.91660624, 23.51480439],
       [ 0.97412264, 17.73925256, 13.52155993]])], dtype=object)

In [18]:
import matplotlib.pyplot as plt

In [21]:
arr_abs.T.shape

(30329,)

In [35]:
arr_abs = np.vstack(list_abs)

In [36]:
arr_abs.shape

(60657, 3)

In [33]:
list_abs[0]

array([[ 0.60915119, 30.91660624, 23.51480439],
       [ 0.97412264, 17.73925256, 13.52155993]])

In [37]:
list_abs = []
for i in range(len(abs_csi)):
    abs_val = np.mean(abs_csi[str(i+1)],axis=2)
    list_abs.append(abs_val)

In [38]:
list_abs

[array([[ 0.60915119, 30.91660624, 23.51480439],
        [ 0.97412264, 17.73925256, 13.52155993]]),
 array([[ 0.63131447, 31.02178012, 23.6458404 ],
        [ 1.03645414, 17.87284508, 13.38988504]]),
 array([[ 0.5625994 , 30.51906035, 23.5827112 ],
        [ 0.98468303, 18.28480207, 13.67957151]]),
 array([[ 0.5687504 , 30.55377416, 29.5242294 ],
        [ 0.98051334, 16.14888574, 17.79568356]]),
 array([[ 0.48963028, 31.37583583, 25.4499049 ],
        [ 0.90971775, 15.853277  , 15.59297289]]),
 array([[ 0.53746123, 31.3224291 , 25.39574232],
        [ 0.94463938, 15.78081015, 15.68497165]]),
 array([[ 0.57570918, 31.01536443, 32.72489375],
        [ 0.88999857, 17.35722528, 14.14106992]]),
 array([[ 0.47771112, 31.42873802, 31.22172265],
        [ 0.74757929, 15.65177855, 15.90605312]]),
 array([[ 0.43648837, 32.24300698, 32.04409731],
        [ 0.82483694, 16.11670036, 16.23986246]]),
 array([[ 0.50396237, 30.0468206 , 28.81587078],
        [ 0.96635032, 16.92545491, 15.26346717]]),


In [39]:
abs_val.shape

(2, 3)

In [40]:
list_abs = []
for i in range(len(abs_csi)):
    abs_val = np.mean(abs_csi[str(i+1)],axis=2)
    list_abs.append(abs_val)

arr_abs = np.array(list_abs)

In [43]:
arr_abs

array([array([[ 0.60915119, 30.91660624, 23.51480439],
       [ 0.97412264, 17.73925256, 13.52155993]]),
       array([[ 0.63131447, 31.02178012, 23.6458404 ],
       [ 1.03645414, 17.87284508, 13.38988504]]),
       array([[ 0.5625994 , 30.51906035, 23.5827112 ],
       [ 0.98468303, 18.28480207, 13.67957151]]),
       ...,
       array([[ 0.84407155, 28.64043525, 33.49510224],
       [ 0.83940854, 16.04660562, 15.65207515]]),
       array([[ 0.65288856, 23.95800098, 31.99759028],
       [ 0.77727812, 11.37855408, 14.20005751]]),
       array([[ 0.68787172, 24.11010191, 32.12800862],
       [ 0.76926707, 11.40111355, 14.47267881]])], dtype=object)