In [1]:
##########################################
## Made by : HERO Kwon
## Title : TER
## Version : v0
## Date : 2018.05.29.
## Description : TER-RM Algorithm
##########################################


# Main

# packages

import numpy as np
import pandas as pd
import scipy as sp
import os
import re
import imageio
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
import random
from sklearn.metrics import confusion_matrix
import time

from sklearn.datasets import load_iris
 
data = load_iris()
data_v = data['data']
data_l = data['target']

data_train = np.array([]).reshape(0,4)
data_test = np.array([]).reshape(0,4)
label_train = np.array([])
label_test = np.array([])

for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    l_train = np.full(shape=len(v_train),fill_value=target)
    l_test = np.full(shape=len(v_test),fill_value=target)
    data_train = np.concatenate((data_train,v_train))
    data_test = np.concatenate((data_train,v_test))
    label_train = np.concatenate((label_train,l_train))
    label_test = np.concatenate((label_test,l_test))

In [2]:
data_train

array([[4.8, 3.4, 1.6, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.4, 3.2, 1.3, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.3, 1.7, 0.5],
       [5.4, 3.4, 1.5, 0.4],
       [4.4, 3. , 1.3, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3.4, 1.5, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.6, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.5, 1.6, 0.6],
       [5.5, 3.5, 1.3, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [5.7, 2.9, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [6.7, 3. , 5. , 1.7],
       [5. , 2. , 3.5, 1. ],
       [5.6, 3. , 4.5, 1.5],
       [6.2, 2.9, 4.3, 1.3],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.8, 4.7, 1.2],
       [5.5, 2

In [5]:
X = data_train

In [8]:
m,l = X.shape

In [9]:
MM1 = []
MM3 = []

In [10]:
sum(X)

array([435.6, 228.8, 281.5,  90.9])

In [12]:
X.shape

(75, 4)

In [13]:
X[:,1]

array([3.4, 3.9, 3.2, 3. , 3.3, 3.4, 3. , 3.4, 3.4, 3.4, 3.5, 2.9, 3.2,
       4. , 3.8, 3.4, 3.6, 3.5, 3.5, 3.5, 3.1, 3.5, 3.2, 3.7, 3.7, 3.1,
       2.9, 3. , 3. , 2. , 3. , 2.9, 2.2, 2.8, 2.5, 2.4, 2.6, 2.9, 3.4,
       2.8, 2.5, 2.7, 3. , 2.7, 2.7, 2.2, 2.9, 3.2, 3. , 2.4, 3. , 3. ,
       3.2, 2.8, 3. , 3.4, 2.7, 2.5, 3. , 2.7, 2.5, 2.8, 3.8, 2.7, 3. ,
       2.8, 3. , 3. , 3.1, 3.2, 3. , 3.1, 2.9, 3. , 3.3])

In [16]:
X[0:5,:]

array([[4.8, 3.4, 1.6, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.4, 3.2, 1.3, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.3, 1.7, 0.5]])

In [18]:
a = np.array()

TypeError: Required argument 'object' (pos 1) not found

In [24]:
np.power(X[:,1],2)

array([11.56, 15.21, 10.24,  9.  , 10.89, 11.56,  9.  , 11.56, 11.56,
       11.56, 12.25,  8.41, 10.24, 16.  , 14.44, 11.56, 12.96, 12.25,
       12.25, 12.25,  9.61, 12.25, 10.24, 13.69, 13.69,  9.61,  8.41,
        9.  ,  9.  ,  4.  ,  9.  ,  8.41,  4.84,  7.84,  6.25,  5.76,
        6.76,  8.41, 11.56,  7.84,  6.25,  7.29,  9.  ,  7.29,  7.29,
        4.84,  8.41, 10.24,  9.  ,  5.76,  9.  ,  9.  , 10.24,  7.84,
        9.  , 11.56,  7.29,  6.25,  9.  ,  7.29,  6.25,  7.84, 14.44,
        7.29,  9.  ,  7.84,  9.  ,  9.  ,  9.61, 10.24,  9.  ,  9.61,
        8.41,  9.  , 10.89])

In [25]:
X[:,1]

array([3.4, 3.9, 3.2, 3. , 3.3, 3.4, 3. , 3.4, 3.4, 3.4, 3.5, 2.9, 3.2,
       4. , 3.8, 3.4, 3.6, 3.5, 3.5, 3.5, 3.1, 3.5, 3.2, 3.7, 3.7, 3.1,
       2.9, 3. , 3. , 2. , 3. , 2.9, 2.2, 2.8, 2.5, 2.4, 2.6, 2.9, 3.4,
       2.8, 2.5, 2.7, 3. , 2.7, 2.7, 2.2, 2.9, 3.2, 3. , 2.4, 3. , 3. ,
       3.2, 2.8, 3. , 3.4, 2.7, 2.5, 3. , 2.7, 2.5, 2.8, 3.8, 2.7, 3. ,
       2.8, 3. , 3. , 3.1, 3.2, 3. , 3.1, 2.9, 3. , 3.3])

In [26]:
3.4**2

11.559999999999999

In [27]:
X[:,1]**2

array([11.56, 15.21, 10.24,  9.  , 10.89, 11.56,  9.  , 11.56, 11.56,
       11.56, 12.25,  8.41, 10.24, 16.  , 14.44, 11.56, 12.96, 12.25,
       12.25, 12.25,  9.61, 12.25, 10.24, 13.69, 13.69,  9.61,  8.41,
        9.  ,  9.  ,  4.  ,  9.  ,  8.41,  4.84,  7.84,  6.25,  5.76,
        6.76,  8.41, 11.56,  7.84,  6.25,  7.29,  9.  ,  7.29,  7.29,
        4.84,  8.41, 10.24,  9.  ,  5.76,  9.  ,  9.  , 10.24,  7.84,
        9.  , 11.56,  7.29,  6.25,  9.  ,  7.29,  6.25,  7.84, 14.44,
        7.29,  9.  ,  7.84,  9.  ,  9.  ,  9.61, 10.24,  9.  ,  9.61,
        8.41,  9.  , 10.89])

In [28]:
a = []

In [37]:
X[:,1]**2

array([11.56, 15.21, 10.24,  9.  , 10.89, 11.56,  9.  , 11.56, 11.56,
       11.56, 12.25,  8.41, 10.24, 16.  , 14.44, 11.56, 12.96, 12.25,
       12.25, 12.25,  9.61, 12.25, 10.24, 13.69, 13.69,  9.61,  8.41,
        9.  ,  9.  ,  4.  ,  9.  ,  8.41,  4.84,  7.84,  6.25,  5.76,
        6.76,  8.41, 11.56,  7.84,  6.25,  7.29,  9.  ,  7.29,  7.29,
        4.84,  8.41, 10.24,  9.  ,  5.76,  9.  ,  9.  , 10.24,  7.84,
        9.  , 11.56,  7.29,  6.25,  9.  ,  7.29,  6.25,  7.84, 14.44,
        7.29,  9.  ,  7.84,  9.  ,  9.  ,  9.61, 10.24,  9.  ,  9.61,
        8.41,  9.  , 10.89])

In [30]:
a

[array([11.56, 15.21, 10.24,  9.  , 10.89, 11.56,  9.  , 11.56, 11.56,
        11.56, 12.25,  8.41, 10.24, 16.  , 14.44, 11.56, 12.96, 12.25,
        12.25, 12.25,  9.61, 12.25, 10.24, 13.69, 13.69,  9.61,  8.41,
         9.  ,  9.  ,  4.  ,  9.  ,  8.41,  4.84,  7.84,  6.25,  5.76,
         6.76,  8.41, 11.56,  7.84,  6.25,  7.29,  9.  ,  7.29,  7.29,
         4.84,  8.41, 10.24,  9.  ,  5.76,  9.  ,  9.  , 10.24,  7.84,
         9.  , 11.56,  7.29,  6.25,  9.  ,  7.29,  6.25,  7.84, 14.44,
         7.29,  9.  ,  7.84,  9.  ,  9.  ,  9.61, 10.24,  9.  ,  9.61,
         8.41,  9.  , 10.89])]

In [51]:
b = np.array([]).reshape(0,4)

In [50]:
data_train = np.array([]).reshape(75,4)

ValueError: cannot reshape array of size 0 into shape (75,4)

In [52]:
    order = 2
    X = data
    m,l = X.shape
    
    MM1 = np.array([]).reshape(0,4)
    MM3 = np.array([]).reshape(0,4)

    Msum = sum(X)

AttributeError: shape

In [53]:
data=data_train

In [54]:
    order = 2
    X = data
    m,l = X.shape

In [55]:
    MM1 = np.array([]).reshape(0,4)
    MM3 = np.array([]).reshape(0,4)

    Msum = sum(X)

In [56]:
i=0
k=0

In [59]:
M1[:,k] = X[:,k]**i

In [58]:
    M1 = np.array([]).reshape(0,4)
    M3 = np.array([]).reshape(0,4)

In [60]:
X

array([], shape=(0, 4), dtype=float64)

In [61]:
data_train

array([], shape=(0, 4), dtype=float64)

In [63]:
data_train = np.array([]).reshape(0,4)
data_test = np.array([]).reshape(0,4)
label_train = np.array([])
label_test = np.array([])

for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    l_train = np.full(shape=len(v_train),fill_value=target)
    l_test = np.full(shape=len(v_test),fill_value=target)
    data_train = np.concatenate((data_train,v_train))
    data_test = np.concatenate((data_train,v_test))
    label_train = np.concatenate((label_train,l_train))
    label_test = np.concatenate((label_test,l_test))


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [64]:
data = load_iris()
data_v = data['data']
data_l = data['target']

data_train = np.array([]).reshape(0,4)
data_test = np.array([]).reshape(0,4)
label_train = np.array([])
label_test = np.array([])

for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    l_train = np.full(shape=len(v_train),fill_value=target)
    l_test = np.full(shape=len(v_test),fill_value=target)
    data_train = np.concatenate((data_train,v_train))
    data_test = np.concatenate((data_train,v_test))
    label_train = np.concatenate((label_train,l_train))
    label_test = np.concatenate((label_test,l_test))

In [65]:
data = data_train

In [66]:
    order = 2
    X = data
    m,l = X.shape
    
    M1 = np.array([]).reshape(0,4)
    M3 = np.array([]).reshape(0,4)

    Msum = sum(X)

In [67]:
M1[:,k] = X[:,k]**(i+1)

ValueError: could not broadcast input array from shape (75) into shape (0)

In [68]:
k

0

In [69]:
i

0

In [70]:
M1.shape

(0, 4)

In [71]:
X.shape

(75, 4)

In [72]:
M1 = np.array([]).reshape(X.shape)

ValueError: cannot reshape array of size 0 into shape (75,4)

In [74]:
a = np.matrix

In [75]:
a.shape

<attribute 'shape' of 'numpy.ndarray' objects>

In [76]:
a[:,k] = X[:,k]**(i+1)

TypeError: 'type' object does not support item assignment

In [77]:
a = np.matrix.reshape(X.shape)

TypeError: descriptor 'reshape' requires a 'numpy.ndarray' object but received a 'tuple'

In [78]:
a = np.empty(shape=X.shape)

In [79]:
a.shape

(75, 4)

In [80]:
a

array([[1.50367901e-311, 1.50365174e-311, 1.50363162e-311,
        1.50369167e-311],
       [1.50368918e-311, 1.50369167e-311, 1.50368736e-311,
        1.50369167e-311],
       [1.50362706e-311, 1.50368938e-311, 1.50368918e-311,
        1.50368926e-311],
       [1.50368926e-311, 1.50368955e-311, 1.50368926e-311,
        1.50363171e-311],
       [1.50368926e-311, 1.50368918e-311, 1.50369167e-311,
        1.50368926e-311],
       [1.50368799e-311, 1.50369167e-311, 1.50363172e-311,
        1.50369160e-311],
       [1.50368918e-311, 1.50369144e-311, 1.50367869e-311,
        1.50369167e-311],
       [1.50369167e-311, 1.50369167e-311, 1.50369167e-311,
        1.50361069e-311],
       [1.50369006e-311, 1.50369167e-311, 1.50363172e-311,
        1.50369160e-311],
       [1.50368918e-311, 1.50362501e-311, 1.50369006e-311,
        1.50369006e-311],
       [1.50368926e-311, 1.50368918e-311, 1.50368795e-311,
        1.50368926e-311],
       [1.50363161e-311, 1.50369144e-311, 1.50368918e-311,
      

In [81]:
    M1 = []
    M3 = []

In [84]:
M1.append(X[:,1]**(i+1))

In [85]:
M1

[array([5.4, 5. , 5.1, 5.4, 5.1, 5.7, 5.1, 5.1, 5.8, 4.8, 5.7, 5.1, 4.9,
        4.6, 5.4, 4.8, 4.9, 5.3, 4.7, 4.8, 4.9, 5. , 5.5, 4.5, 5.2, 5.7,
        6.9, 5.6, 5.6, 6. , 5.7, 6.7, 6.4, 6.2, 5.9, 6. , 5.6, 5.6, 5.1,
        5.9, 5.4, 6.5, 5. , 5.5, 6.4, 6.1, 5.8, 5.5, 5. , 5.5, 6.3, 7.9,
        7.3, 6. , 6.7, 5.7, 6.1, 7.7, 7.2, 7.2, 7.7, 7.4, 6.9, 6.3, 6.5,
        6.7, 6.2, 6. , 6.9, 6.8, 6.7, 7.1, 5.8, 6.1, 6.2]),
 array([3.4, 3.6, 3.5, 3.9, 3.7, 4.4, 3.3, 3.8, 4. , 3.4, 3.8, 3.8, 3.1,
        3.4, 3.9, 3. , 3.1, 3.7, 3.2, 3.4, 3. , 3.4, 3.5, 2.3, 3.4, 2.6,
        3.1, 2.5, 2.9, 3.4, 2.9, 3.1, 2.9, 2.2, 3.2, 2.2, 3. , 2.7, 2.5,
        3. , 3. , 2.8, 2.3, 2.4, 3.2, 2.9, 2.7, 2.5, 2. , 2.6, 2.5, 3.8,
        2.9, 2.2, 3.3, 2.5, 2.6, 2.6, 3.6, 3. , 2.8, 2.8, 3.1, 3.4, 3. ,
        3.3, 2.8, 3. , 3.1, 3.2, 3.1, 3. , 2.8, 3. , 3.4])]

In [87]:
np.array(M1).shape

(2, 75)

In [89]:
X.shape

(75, 4)

In [92]:
Msum.shape

(4,)

In [93]:
X.shape

(75, 4)

In [94]:
X[:,0] * Msum

ValueError: operands could not be broadcast together with shapes (75,) (4,) 

In [102]:
np.sum(X,axis=1).T.shape

(75,)

In [103]:
Msum = np.sum(X,axis=1)

In [104]:
X[:,k]*Msum

array([ 57.78,  51.  ,  52.53,  61.56,  54.57,  68.4 ,  54.06,  54.57,
        64.96,  48.  ,  65.55,  57.12,  47.04,  44.62,  59.4 ,  44.64,
        47.04,  56.71,  45.59,  49.44,  46.55,  52.  ,  57.75,  37.8 ,
        53.04,  72.96, 113.16,  73.36,  75.04,  93.  ,  80.37, 104.52,
        95.36,  89.28,  92.63,  79.2 ,  81.76,  77.28,  59.67,  86.14,
        77.76, 100.1 ,  58.  ,  70.4 ,  99.84,  92.11,  78.88,  73.15,
        57.5 ,  75.35,  98.91, 158.79, 133.59,  88.2 , 119.26,  86.64,
        95.77, 150.15, 139.68, 126.72, 147.84, 134.68, 120.75, 111.51,
       109.2 , 121.94,  96.72,  93.6 , 120.06, 123.76, 119.26, 128.51,
        93.38,  96.38, 107.26])

In [105]:
X.shape

(75, 4)

In [106]:
Msum.shape

(75,)

In [107]:
X[:,k]*Msum**(i)

array([5.4, 5. , 5.1, 5.4, 5.1, 5.7, 5.1, 5.1, 5.8, 4.8, 5.7, 5.1, 4.9,
       4.6, 5.4, 4.8, 4.9, 5.3, 4.7, 4.8, 4.9, 5. , 5.5, 4.5, 5.2, 5.7,
       6.9, 5.6, 5.6, 6. , 5.7, 6.7, 6.4, 6.2, 5.9, 6. , 5.6, 5.6, 5.1,
       5.9, 5.4, 6.5, 5. , 5.5, 6.4, 6.1, 5.8, 5.5, 5. , 5.5, 6.3, 7.9,
       7.3, 6. , 6.7, 5.7, 6.1, 7.7, 7.2, 7.2, 7.7, 7.4, 6.9, 6.3, 6.5,
       6.7, 6.2, 6. , 6.9, 6.8, 6.7, 7.1, 5.8, 6.1, 6.2])

In [108]:
X[:,k]

array([5.4, 5. , 5.1, 5.4, 5.1, 5.7, 5.1, 5.1, 5.8, 4.8, 5.7, 5.1, 4.9,
       4.6, 5.4, 4.8, 4.9, 5.3, 4.7, 4.8, 4.9, 5. , 5.5, 4.5, 5.2, 5.7,
       6.9, 5.6, 5.6, 6. , 5.7, 6.7, 6.4, 6.2, 5.9, 6. , 5.6, 5.6, 5.1,
       5.9, 5.4, 6.5, 5. , 5.5, 6.4, 6.1, 5.8, 5.5, 5. , 5.5, 6.3, 7.9,
       7.3, 6. , 6.7, 5.7, 6.1, 7.7, 7.2, 7.2, 7.7, 7.4, 6.9, 6.3, 6.5,
       6.7, 6.2, 6. , 6.9, 6.8, 6.7, 7.1, 5.8, 6.1, 6.2])

In [109]:
i

0

In [111]:
    order = 2
    X = data
    m,l = X.shape
    
    M1 = []
    M2 = []
    M3 = []

    Msum = np.sum(X,axis=1)

    for i in range(order):
        for k in range(l):
            M1.append(X[:,k]**(i+1))
            if (i>0):
                M3.append(X[:,k]*Msum**(i)) 
    M2.append(Msum**(i+1))

In [112]:
M2

[array([114.49, 104.04, 106.09, 129.96, 114.49, 144.  , 112.36, 114.49,
        125.44, 100.  , 132.25, 125.44,  92.16,  94.09, 121.  ,  86.49,
         92.16, 114.49,  94.09, 106.09,  90.25, 108.16, 110.25,  70.56,
        104.04, 163.84, 268.96, 171.61, 179.56, 240.25, 198.81, 243.36,
        222.01, 207.36, 246.49, 174.24, 213.16, 190.44, 136.89, 213.16,
        207.36, 237.16, 134.56, 163.84, 243.36, 228.01, 184.96, 176.89,
        132.25, 187.69, 246.49, 404.01, 334.89, 216.09, 316.84, 231.04,
        246.49, 380.25, 376.36, 309.76, 368.64, 331.24, 306.25, 313.29,
        282.24, 331.24, 243.36, 243.36, 302.76, 331.24, 316.84, 327.61,
        259.21, 249.64, 299.29])]

In [114]:
len(M1)

8

In [115]:
X.shape

(75, 4)

In [116]:
range(l)

range(0, 4)

In [117]:
X.shape

(75, 4)

In [123]:
[np.ones(X.shape[0]),MM1]

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.]), array([], shape=(0, 4), dtype=float64)]

In [125]:
MM1

array([], shape=(0, 4), dtype=float64)

In [126]:
    m,l = X.shape
    
    M1 = []
    M2 = []
    M3 = []
    MM1 = []
    MM3 = []

    Msum = np.sum(X,axis=1)

    for i in range(order):
        for k in range(l):
            M1.append(X[:,k]**(i+1))
            if (i>0):
                M3.append(X[:,k]*Msum**(i)) 

        M2.append(Msum**(i+1))
        MM1.append(M1)
        if (i>0):
            MM3.append(M3)

In [128]:
len(MM1)

2

In [130]:
MM1

[[array([5.4, 5. , 5.1, 5.4, 5.1, 5.7, 5.1, 5.1, 5.8, 4.8, 5.7, 5.1, 4.9,
         4.6, 5.4, 4.8, 4.9, 5.3, 4.7, 4.8, 4.9, 5. , 5.5, 4.5, 5.2, 5.7,
         6.9, 5.6, 5.6, 6. , 5.7, 6.7, 6.4, 6.2, 5.9, 6. , 5.6, 5.6, 5.1,
         5.9, 5.4, 6.5, 5. , 5.5, 6.4, 6.1, 5.8, 5.5, 5. , 5.5, 6.3, 7.9,
         7.3, 6. , 6.7, 5.7, 6.1, 7.7, 7.2, 7.2, 7.7, 7.4, 6.9, 6.3, 6.5,
         6.7, 6.2, 6. , 6.9, 6.8, 6.7, 7.1, 5.8, 6.1, 6.2]),
  array([3.4, 3.6, 3.5, 3.9, 3.7, 4.4, 3.3, 3.8, 4. , 3.4, 3.8, 3.8, 3.1,
         3.4, 3.9, 3. , 3.1, 3.7, 3.2, 3.4, 3. , 3.4, 3.5, 2.3, 3.4, 2.6,
         3.1, 2.5, 2.9, 3.4, 2.9, 3.1, 2.9, 2.2, 3.2, 2.2, 3. , 2.7, 2.5,
         3. , 3. , 2.8, 2.3, 2.4, 3.2, 2.9, 2.7, 2.5, 2. , 2.6, 2.5, 3.8,
         2.9, 2.2, 3.3, 2.5, 2.6, 2.6, 3.6, 3. , 2.8, 2.8, 3.1, 3.4, 3. ,
         3.3, 2.8, 3. , 3.1, 3.2, 3.1, 3. , 2.8, 3. , 3.4]),
  array([1.7, 1.4, 1.4, 1.7, 1.5, 1.5, 1.7, 1.6, 1.2, 1.6, 1.7, 1.9, 1.5,
         1.4, 1.3, 1.4, 1.5, 1.5, 1.6, 1.9, 1.4, 1.6, 1.3, 1.3, 

In [131]:
MM1 = np.array(MM1)

In [132]:
MM1.shape

(2, 8, 75)

In [134]:
MM1.T.shape

(75, 8, 2)

In [136]:
MM1[0].shape

(8, 75)

In [137]:
np.array(M1).shape

(8, 75)

In [138]:
    m,l = X.shape
    
    M1 = []
    M2 = []
    M3 = []
    MM1 = []
    MM3 = []

    Msum = np.sum(X,axis=1)

    for i in range(order):
        for k in range(l):
            M1.append(X[:,k]**(i+1))
            if (i>0):
                M3.append(X[:,k]*Msum**(i)) 
        M1 = np.array(M1).T
        M3 = np.array(M3).T
        M2.append(Msum**(i+1))
        MM1.append(M1)
        if (i>0):
            MM3.append(M3)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [139]:
    m,l = X.shape
    
    M1 = []
    M2 = []
    M3 = []
    MM1 = []
    MM3 = []

    Msum = np.sum(X,axis=1)

    for i in range(order):
        for k in range(l):
            M1.append(X[:,k]**(i+1))
            if (i>0):
                M3.append(X[:,k]*Msum**(i)) 
        M2.append(Msum**(i+1))
        MM1.append(np.array(M1).T)
        if (i>0):
            MM3.append(np.array(M3).T)
    MM1 = np.array(MM1)
    P = [np.ones(X.shape[0])]

ValueError: could not broadcast input array from shape (75,4) into shape (75)

In [140]:
    m,l = X.shape
    
    M1 = []
    M2 = []
    M3 = []
    MM1 = []
    MM3 = []

    Msum = np.sum(X,axis=1)

    for i in range(order):
        for k in range(l):
            M1.append(X[:,k]**(i+1))
            if (i>0):
                M3.append(X[:,k]*Msum**(i)) 
        M2.append(Msum**(i+1))
        MM1.append(np.array(M1).T)
        if (i>0):
            MM3.append(np.array(M3).T)
    P = [np.ones(X.shape[0])]

In [141]:
MM1

[array([[5.4, 3.4, 1.7, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.1, 3.5, 1.4, 0.3],
        [5.4, 3.9, 1.7, 0.4],
        [5.1, 3.7, 1.5, 0.4],
        [5.7, 4.4, 1.5, 0.4],
        [5.1, 3.3, 1.7, 0.5],
        [5.1, 3.8, 1.6, 0.2],
        [5.8, 4. , 1.2, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.9, 0.4],
        [4.9, 3.1, 1.5, 0.1],
        [4.6, 3.4, 1.4, 0.3],
        [5.4, 3.9, 1.3, 0.4],
        [4.8, 3. , 1.4, 0.1],
        [4.9, 3.1, 1.5, 0.1],
        [5.3, 3.7, 1.5, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.4, 1.9, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.5, 3.5, 1.3, 0.2],
        [4.5, 2.3, 1.3, 0.3],
        [5.2, 3.4, 1.4, 0.2],
        [5.7, 2.6, 3.5, 1. ],
        [6.9, 3.1, 4.9, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.6, 2.9, 3.6, 1.3],
        [6. , 3.4, 4.5, 1.6],
        [5.7, 2.9, 4.2, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [6.4, 2.9, 4.3, 1.3],
        [6

In [142]:
    m,l = X.shape
    
    M1 = []
    M2 = []
    M3 = []
    MM1 = []
    MM3 = []

    Msum = np.sum(X,axis=1)

    for i in range(order):
        for k in range(l):
            M1.append(X[:,k]**(i+1))
            if (i>0):
                M3.append(X[:,k]*Msum**(i)) 
        M2.append(Msum**(i+1))
        MM1.append(np.array(M1).T)
        if (i>0):
            MM3.append(np.array(M3).T)
    P = [np.ones(X.shape[0])]

In [143]:
MM1

[array([[5.4, 3.4, 1.7, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.1, 3.5, 1.4, 0.3],
        [5.4, 3.9, 1.7, 0.4],
        [5.1, 3.7, 1.5, 0.4],
        [5.7, 4.4, 1.5, 0.4],
        [5.1, 3.3, 1.7, 0.5],
        [5.1, 3.8, 1.6, 0.2],
        [5.8, 4. , 1.2, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.9, 0.4],
        [4.9, 3.1, 1.5, 0.1],
        [4.6, 3.4, 1.4, 0.3],
        [5.4, 3.9, 1.3, 0.4],
        [4.8, 3. , 1.4, 0.1],
        [4.9, 3.1, 1.5, 0.1],
        [5.3, 3.7, 1.5, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.4, 1.9, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.5, 3.5, 1.3, 0.2],
        [4.5, 2.3, 1.3, 0.3],
        [5.2, 3.4, 1.4, 0.2],
        [5.7, 2.6, 3.5, 1. ],
        [6.9, 3.1, 4.9, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.6, 2.9, 3.6, 1.3],
        [6. , 3.4, 4.5, 1.6],
        [5.7, 2.9, 4.2, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [6.4, 2.9, 4.3, 1.3],
        [6

In [144]:
    m,l = X.shape
    
    M1 = []
    M2 = []
    M3 = []
    MM1 = []
    MM3 = []

    Msum = np.sum(X,axis=1)

    for i in range(order):
        for k in range(l):
            M1.append(X[:,k]**(i+1))
            if (i>0):
                M3.append(X[:,k]*Msum**(i)) 
        M2.append(Msum**(i+1))
        MM1.append(M1)
        if (i>0):
            MM3.append(M3)

In [145]:
MM1

[[array([5.4, 5. , 5.1, 5.4, 5.1, 5.7, 5.1, 5.1, 5.8, 4.8, 5.7, 5.1, 4.9,
         4.6, 5.4, 4.8, 4.9, 5.3, 4.7, 4.8, 4.9, 5. , 5.5, 4.5, 5.2, 5.7,
         6.9, 5.6, 5.6, 6. , 5.7, 6.7, 6.4, 6.2, 5.9, 6. , 5.6, 5.6, 5.1,
         5.9, 5.4, 6.5, 5. , 5.5, 6.4, 6.1, 5.8, 5.5, 5. , 5.5, 6.3, 7.9,
         7.3, 6. , 6.7, 5.7, 6.1, 7.7, 7.2, 7.2, 7.7, 7.4, 6.9, 6.3, 6.5,
         6.7, 6.2, 6. , 6.9, 6.8, 6.7, 7.1, 5.8, 6.1, 6.2]),
  array([3.4, 3.6, 3.5, 3.9, 3.7, 4.4, 3.3, 3.8, 4. , 3.4, 3.8, 3.8, 3.1,
         3.4, 3.9, 3. , 3.1, 3.7, 3.2, 3.4, 3. , 3.4, 3.5, 2.3, 3.4, 2.6,
         3.1, 2.5, 2.9, 3.4, 2.9, 3.1, 2.9, 2.2, 3.2, 2.2, 3. , 2.7, 2.5,
         3. , 3. , 2.8, 2.3, 2.4, 3.2, 2.9, 2.7, 2.5, 2. , 2.6, 2.5, 3.8,
         2.9, 2.2, 3.3, 2.5, 2.6, 2.6, 3.6, 3. , 2.8, 2.8, 3.1, 3.4, 3. ,
         3.3, 2.8, 3. , 3.1, 3.2, 3.1, 3. , 2.8, 3. , 3.4]),
  array([1.7, 1.4, 1.4, 1.7, 1.5, 1.5, 1.7, 1.6, 1.2, 1.6, 1.7, 1.9, 1.5,
         1.4, 1.3, 1.4, 1.5, 1.5, 1.6, 1.9, 1.4, 1.6, 1.3, 1.3, 

In [146]:
len(MM1)

2

In [149]:
np.array(MM1[0]).shape

(8, 75)

In [150]:
len(M2)

2

In [151]:
M2[0]

array([10.7, 10.2, 10.3, 11.4, 10.7, 12. , 10.6, 10.7, 11.2, 10. , 11.5,
       11.2,  9.6,  9.7, 11. ,  9.3,  9.6, 10.7,  9.7, 10.3,  9.5, 10.4,
       10.5,  8.4, 10.2, 12.8, 16.4, 13.1, 13.4, 15.5, 14.1, 15.6, 14.9,
       14.4, 15.7, 13.2, 14.6, 13.8, 11.7, 14.6, 14.4, 15.4, 11.6, 12.8,
       15.6, 15.1, 13.6, 13.3, 11.5, 13.7, 15.7, 20.1, 18.3, 14.7, 17.8,
       15.2, 15.7, 19.5, 19.4, 17.6, 19.2, 18.2, 17.5, 17.7, 16.8, 18.2,
       15.6, 15.6, 17.4, 18.2, 17.8, 18.1, 16.1, 15.8, 17.3])

In [158]:
np.array(MM1).T.shape

(75, 8, 2)

In [159]:
a = np.array(MM1).T

In [160]:
aa = a.flatten()

In [161]:
aa.shape

(1200,)

In [166]:
aa = np.squeeze(a,axis=2)

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [163]:
a.shape

(75, 8, 2)