In [1]:
# packages

import numpy as np
import pandas as pd
import scipy as sp
import os
import re
import imageio
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
import random
from sklearn.metrics import confusion_matrix
import time

from sklearn.datasets import load_iris
 
data = load_iris()

In [6]:
type(data)

sklearn.utils.Bunch

In [7]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [9]:
data.data.shape

(150, 4)

In [10]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [15]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [17]:
data_train = pd.DataFrame()
data_test = pd.DataFrame()


In [18]:
data_train, data_test = train_test_split(data,test_size = 0.2)

KeyError: 3

In [19]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [22]:
set(data.target)

{0, 1, 2}

In [27]:
data(data.target=='0')

C:\Users\herok\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.


TypeError: 'Bunch' object is not callable

In [28]:
data[target=='0']

NameError: name 'target' is not defined

In [34]:
data:data['target']==0

In [38]:
data[1]

KeyError: 1

In [2]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [8]:
list(set(data.target))[0]

0

In [10]:
a = pd.Series(data) 

In [16]:
a.keys()

Index(['DESCR', 'data', 'feature_names', 'target', 'target_names'], dtype='object')

In [23]:
a.loc[[a['target']==0]]

ValueError: too many values to unpack (expected 1)

In [25]:
aa = a['target'==0] 

In [29]:
aa.data

AttributeError: 'str' object has no attribute 'data'

In [30]:
aa.keys()

AttributeError: 'str' object has no attribute 'keys'

In [33]:
b = pd.DataFrame(data)

ValueError: arrays must all be same length

In [36]:
a.keys()

Index(['DESCR', 'data', 'feature_names', 'target', 'target_names'], dtype='object')

In [40]:
aa = a['target'==0]

In [41]:
len(aa)

2675

In [42]:
type(aa)

str

In [43]:
len(a)

5

In [49]:
a.index

Index(['DESCR', 'data', 'feature_names', 'target', 'target_names'], dtype='object')

In [56]:
a.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [57]:
type(a)

pandas.core.series.Series

In [58]:
a.loc[a['target']==0]

KeyError: IndexError('index 5 is out of bounds for axis 0 with size 5',)

In [59]:
a.index

Index(['DESCR', 'data', 'feature_names', 'target', 'target_names'], dtype='object')

In [60]:
len(a)

5

In [61]:
a

DESCR            Iris Plants Database\n====================\n\n...
data             [[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2], [...
feature_names    [sepal length (cm), sepal width (cm), petal le...
target           [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
target_names                       [setosa, versicolor, virginica]
dtype: object

In [67]:
dd = data['data'].shape

In [68]:
dd[data['target']==0]

TypeError: only integer scalar arrays can be converted to a scalar index

In [71]:
dd[int(data['target']==0)]

TypeError: only size-1 arrays can be converted to Python scalars

In [79]:
dd.shape()

AttributeError: 'tuple' object has no attribute 'shape'

In [80]:
dd = data['data']

In [83]:
dd[data['target']==0].shape

(50, 4)

In [86]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [90]:
set(data['target'])

{0, 1, 2}

In [93]:
data_train = np.array([])

In [94]:
for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    data_train = data_train.append(v_train)
    data_test = data_test.append(v_test)

NameError: name 'data_v' is not defined

In [95]:
data = load_iris()
data_v = data['data']
data_l = data['target']

data_train = np.array([])
data_test = np.array([])


In [96]:
for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    data_train = data_train.append(v_train)
    data_test = data_test.append(v_test)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [98]:
data_train = np.append(data_train,v_train)

In [99]:
for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    data_train = np.append(data_train,v_train)
    data_test = np.append(data_test,v_test)

In [100]:
data_train.shape

(400,)

In [101]:
data_test.shape

(300,)

In [102]:
data_train

array([4.7, 3.2, 1.6, 0.2, 4.8, 3.1, 1.6, 0.2, 4.8, 3. , 1.4, 0.1, 4.4,
       3. , 1.3, 0.2, 4.9, 3. , 1.4, 0.2, 4.6, 3.6, 1. , 0.2, 5.1, 3.3,
       1.7, 0.5, 5.1, 3.7, 1.5, 0.4, 5.4, 3.4, 1.7, 0.2, 5. , 3.3, 1.4,
       0.2, 5.1, 3.8, 1.6, 0.2, 4.6, 3.2, 1.4, 0.2, 5.5, 4.2, 1.4, 0.2,
       4.9, 3.1, 1.5, 0.1, 4.8, 3.4, 1.6, 0.2, 5.4, 3.9, 1.7, 0.4, 4.3,
       3. , 1.1, 0.1, 5.1, 3.5, 1.4, 0.3, 5.2, 3.4, 1.4, 0.2, 5. , 3.4,
       1.6, 0.4, 4.6, 3.4, 1.4, 0.3, 5.4, 3.7, 1.5, 0.2, 5.1, 3.5, 1.4,
       0.2, 5. , 3.6, 1.4, 0.2, 5.7, 4.4, 1.5, 0.4, 5.1, 3.5, 1.4, 0.2,
       5. , 3.5, 1.6, 0.6, 5.1, 3.3, 1.7, 0.5, 4.9, 3. , 1.4, 0.2, 4.8,
       3. , 1.4, 0.3, 5.1, 3.8, 1.5, 0.3, 4.7, 3.2, 1.3, 0.2, 4.4, 2.9,
       1.4, 0.2, 4.5, 2.3, 1.3, 0.3, 5.1, 3.4, 1.5, 0.2, 5. , 3.4, 1.5,
       0.2, 5. , 3.6, 1.4, 0.2, 5.1, 3.7, 1.5, 0.4, 5.4, 3.4, 1.5, 0.4,
       5. , 3.4, 1.6, 0.4, 5.2, 3.5, 1.5, 0.2, 4.9, 3.1, 1.5, 0.1, 5.8,
       4. , 1.2, 0.2, 5.2, 3.4, 1.4, 0.2, 5. , 3. , 1.6, 0.2, 5.

In [103]:
for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    data_train = np.append(data_train,v_train,axis=0)
    data_test = np.append(data_test,v_test,axis=0)


ValueError: all the input arrays must have same number of dimensions

In [104]:
for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    data_train = np.append(data_train,v_train,axis=1)
    data_test = np.append(data_test,v_test,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [105]:
data = load_iris()
data_v = data['data']
data_l = data['target']

data_train = np.array([])
data_test = np.array([])

In [106]:
for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    data_train = np.append(data_train,v_train,axis=1)
    data_test = np.append(data_test,v_test,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [107]:
data = load_iris()
data_v = data['data']
data_l = data['target']

data_train = np.array([])
data_test = np.array([])

for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    data_train = np.append(data_train,v_train,axis=0)
    data_test = np.append(data_test,v_test,axis=0)

ValueError: all the input arrays must have same number of dimensions

In [108]:
data = load_iris()
data_v = data['data']
data_l = data['target']

data_train = np.array([])
data_test = np.array([])

In [109]:
target = 0

In [110]:
v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)

In [111]:
v_train.shape

(25, 4)

In [112]:
v_test.shape

(25, 4)

In [113]:
v_train

array([[5. , 3. , 1.6, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [5.5, 4.2, 1.4, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [4.8, 3. , 1.4, 0.1],
       [5.2, 4.1, 1.5, 0.1],
       [5.7, 4.4, 1.5, 0.4],
       [5. , 3.4, 1.5, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.2, 3.4, 1.4, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5. , 3.6, 1.4, 0.2]])

In [114]:
data_train

array([], dtype=float64)

In [116]:
data_train = np.append(data_train,v_train,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [129]:
data_train = np.empty(shape=[10,4])

In [130]:
data_train.shape

(10, 4)

In [126]:
data_train = np.append(data_train,v_train)

In [127]:
data_train.shape

(100,)

In [128]:
v_train.shape

(25, 4)

In [131]:
data_train

array([[1.20052542e-311, 1.20052542e-311, 1.20052140e-311,
        1.20052451e-311],
       [1.20052352e-311, 1.20052451e-311, 1.20052131e-311,
        1.20051911e-311],
       [1.20052484e-311, 1.20052131e-311, 1.20052542e-311,
        1.20052181e-311],
       [1.20052221e-311, 1.20052181e-311, 1.20052451e-311,
        1.20051924e-311],
       [1.20052555e-311, 1.20052484e-311, 1.20052131e-311,
        1.20052140e-311],
       [1.20052451e-311, 1.20052451e-311, 1.20052379e-311,
        1.20052546e-311],
       [1.20052352e-311, 1.20052140e-311, 1.20052546e-311,
        1.20052181e-311],
       [1.20052542e-311, 1.20052483e-311, 1.20052451e-311,
        1.20052555e-311],
       [1.20052221e-311, 1.20052181e-311, 1.20052546e-311,
        1.20052555e-311],
       [1.20052379e-311, 1.20052546e-311, 1.20052451e-311,
        1.20052379e-311]])

In [136]:
data_train = np.array([])

In [137]:
data_train = np.vstack((data_train,v_train))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [142]:
data_train = np.array([]).reshape(0,4)

In [143]:
data_train = np.concatenate((data_train,v_train))

In [144]:
data_train.shape

(25, 4)

In [141]:
data_train

array([5. , 3. , 1.6, 0.2, 4.9, 3.1, 1.5, 0.1, 5.8, 4. , 1.2, 0.2, 4.4,
       3.2, 1.3, 0.2, 5.5, 4.2, 1.4, 0.2, 4.4, 3. , 1.3, 0.2, 4.4, 2.9,
       1.4, 0.2, 5. , 3.3, 1.4, 0.2, 5.1, 3.5, 1.4, 0.2, 5.4, 3.9, 1.7,
       0.4, 5.4, 3.9, 1.3, 0.4, 4.8, 3. , 1.4, 0.1, 5.2, 4.1, 1.5, 0.1,
       5.7, 4.4, 1.5, 0.4, 5. , 3.4, 1.5, 0.2, 4.9, 3. , 1.4, 0.2, 5.1,
       3.3, 1.7, 0.5, 4.8, 3.4, 1.9, 0.2, 5.5, 3.5, 1.3, 0.2, 5. , 3.5,
       1.6, 0.6, 5.2, 3.4, 1.4, 0.2, 5.1, 3.7, 1.5, 0.4, 5.4, 3.7, 1.5,
       0.2, 4.3, 3. , 1.1, 0.1, 5. , 3.6, 1.4, 0.2])

In [145]:
data = load_iris()
data_v = data['data']
data_l = data['target']

data_train = np.array([]).reshape(0,4)
data_test = np.array([]).reshape(0,4)

for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    data_train = np.concatenate((data_train,v_train))
    data_test = np.concatenate((data_train,v_test))

In [146]:
data_train.shape

(75, 4)

In [150]:
np.full(shape=len(data_train),fill_value=target).shape

(75,)

In [153]:
data_l[data_l==target]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [158]:
data_l[0:len(v_train)].shape

(25,)

In [159]:
label_train = np.array([])
label_test = np.array([])

In [160]:
for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    l_train = data_l[0:len(v_train)]
    l_test = data_l[0:len(v_test)]
    data_train = np.concatenate((data_train,v_train))
    data_test = np.concatenate((data_train,v_test))
    label_train = np.concatenate((label_train,l_train))

In [161]:
label_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [162]:
data = load_iris()
data_v = data['data']
data_l = data['target']

data_train = np.array([]).reshape(0,4)
data_test = np.array([]).reshape(0,4)
label_train = np.array([])
label_test = np.array([])

for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    l_train = data_l[data_l==target][0:len(v_train)]
    l_test = data_l[data_l==target][0:len(v_test)]
    data_train = np.concatenate((data_train,v_train))
    data_test = np.concatenate((data_train,v_test))
    label_train = np.concatenate((label_train,l_train))
    label_test = np.concatenate((label_test,l_test))


In [163]:
label_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [164]:
data_v = data['data']
data_l = data['target']

data_train = np.array([]).reshape(0,4)
data_test = np.array([]).reshape(0,4)
label_train = np.array([])
label_test = np.array([])

for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    l_train = data_l[data_l==target][0:len(v_train)]
    l_test = data_l[data_l==target][0:len(v_test)]
    data_train = np.concatenate((data_train,v_train))
    data_test = np.concatenate((data_train,v_test))
    label_train = np.concatenate((label_train,l_train))
    label_test = np.concatenate((label_test,l_test))

In [165]:
label_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2.])

In [166]:
np.full(shape=len(v_train),fill_value=target)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2])

In [167]:
data = load_iris()
data_v = data['data']
data_l = data['target']

data_train = np.array([]).reshape(0,4)
data_test = np.array([]).reshape(0,4)
label_train = np.array([])
label_test = np.array([])

for target in list(set(data['target'])):
    v_train, v_test = train_test_split(data_v[data_l==target],test_size = 0.5)
    l_train = np.full(shape=len(v_train),fill_value=target)
    l_test = np.full(shape=len(v_test),fill_value=target)
    data_train = np.concatenate((data_train,v_train))
    data_test = np.concatenate((data_train,v_test))
    label_train = np.concatenate((label_train,l_train))
    label_test = np.concatenate((label_test,l_test))

In [168]:
label_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2.])