In [1]:
# Getting CSI Avg
# Made by : HERO Kwon
# Date : 190108

import os
import numpy as np
import pandas as pd
import pickle
import gzip
import matplotlib.pyplot as plt

In [13]:
# data path
#path_info = '/home/herokwon/mount_data/Data/Wi-Fi_infos/'
#path_csi = '/home/herokwon/mount_data/Data/Wi-Fi_processed/'
#path_csi_np = '/home/herokwon/mount_data/Data/Wi-Fi_processed_npy/'
path_csi = 'D:\\Data\\Wi-Fi_processed\\'
path_csi_np = 'D:\\Data\\Wi-Fi_processed_npy\\'
path_meta = 'D:\\Data\\Wi-Fi_meta\\'

# data info
df_info = pd.read_csv('data_subc_sig_v1.csv')
person_uid = np.unique(df_info['id_person'])
dict_id = dict(zip(person_uid,np.arange(len(person_uid))))
csi_time = 15000 #int(np.max(df_info['len']))


In [14]:
# data generator
def gen_csi(df_info,len_num):
    for file in np.unique(df_info.id.values):
        # read sample data
        # load and uncompress.
        with gzip.open(path_csi+file+'.pickle.gz','rb') as f:
            data1 = pickle.load(f)
        data1_diff = data1 #np.diff(data1,axis=0)
        # zero pad
        pad_len = len_num - data1_diff.shape[0]
        data1_pad = np.pad(data1_diff,((0,pad_len),(0,0),(0,0),(0,0)),'constant',constant_values=0)

        yield(data1_pad)

In [15]:
dict_avgcsi = {}
person_id = person_uid[0]

In [16]:
    df1 = df_info[df_info.id_person == person_id]
    df1_uid = np.unique(df1.id.values)

    sum_array = np.zeros([csi_time,30,2,3],dtype=complex)
    gen = gen_csi(df1,csi_time)


In [17]:
array1 = next(gen)

In [18]:
array1.shape

(15000, 30, 2, 3)

In [46]:
array1_num = array1[array1!=0j].reshape([-1,30,2,3])
array1

array([[[[ 10.67085966+15.7254774j ,  23.02659191 +8.98598709j,
           25.83471287 -7.8627387j ],
         [ 16.28710159-21.90334352j,   1.12324839-26.95796126j,
          -13.47898063-23.02659191j]],

        [[-21.90334352-13.47898063j, -25.27308868 +0.j        ,
          -21.90334352+11.79410805j],
         [-13.47898063+21.34171933j,  -1.68487258+23.5882161j ,
           10.10923547+20.78009513j]],

        [[ 18.53359836+14.04060482j,  22.46496771 +3.93136935j,
           23.02659191 -1.12324839j],
         [ 18.53359836-12.35573224j,  11.79410805-18.53359836j,
            2.24649677-21.90334352j]],

        ...,

        [[ 23.02659191 -8.98598709j,  15.7254774 -21.34171933j,
            9.54761128-23.02659191j],
         [ -4.49299354-25.83471287j, -16.28710159-19.65684675j,
          -23.02659191 -7.30111451j]],

        [[-23.02659191 +5.61624193j, -17.41034998+15.7254774j ,
           -8.42436289+21.34171933j],
         [  5.05461774+22.46496771j,  15.16385321+15.7254774

In [45]:
array1_res

array([[[[ 10.67085966+15.7254774j ,  23.02659191 +8.98598709j,
           25.83471287 -7.8627387j ],
         [ 16.28710159-21.90334352j,   1.12324839-26.95796126j,
          -13.47898063-23.02659191j]],

        [[-21.90334352-13.47898063j, -25.27308868 +0.j        ,
          -21.90334352+11.79410805j],
         [-13.47898063+21.34171933j,  -1.68487258+23.5882161j ,
           10.10923547+20.78009513j]],

        [[ 18.53359836+14.04060482j,  22.46496771 +3.93136935j,
           23.02659191 -1.12324839j],
         [ 18.53359836-12.35573224j,  11.79410805-18.53359836j,
            2.24649677-21.90334352j]],

        ...,

        [[ 23.02659191 -8.98598709j,  15.7254774 -21.34171933j,
            9.54761128-23.02659191j],
         [ -4.49299354-25.83471287j, -16.28710159-19.65684675j,
          -23.02659191 -7.30111451j]],

        [[-23.02659191 +5.61624193j, -17.41034998+15.7254774j ,
           -8.42436289+21.34171933j],
         [  5.05461774+22.46496771j,  15.16385321+15.7254774

In [19]:
sum_array += array1

In [20]:
avg_array = sum_array / len(df1_uid)

In [21]:
avg_array.shape

(15000, 30, 2, 3)

In [23]:
aa = np.angle(avg_array)

In [30]:
aa.shape
aa

array([[[[ 0.97459719,  0.37206776, -0.29544084],
         [-0.93141042, -1.52915375, -2.10038593]],

        [[-2.58993767,  3.14159265,  2.64765128],
         [ 2.13411259,  1.64210379,  1.11801785]],

        [[ 0.64833199,  0.17324567, -0.04874185],
         [-0.5880026 , -1.00406711, -1.46858961]],

        ...,

        [[-0.37206776, -0.93576959, -1.17773831],
         [-1.74298714, -2.26271771, -2.83454692]],

        [[ 2.90236105,  2.40699819,  1.94675728],
         [ 1.34948188,  0.80357798,  0.20232163]],

        [[-0.33787819, -1.00406711, -1.62337939],
         [-2.2763645 , -3.03485698,  2.85779854]]],


       [[[-0.64350111, -1.59351969, -2.51428446],
         [ 2.86329299,  1.96249627,  1.11649424]],

        [[ 0.348771  , -0.453844  , -1.24224316],
         [-2.04464766, -2.81254296,  2.66719277]],

        [[ 1.90747115,  1.17227388,  0.78539816],
         [-0.02499479, -0.74969905, -1.49402444]],

        ...,

        [[ 0.74065193, -0.06241881, -0.45471927],
  

In [34]:
a1 = np.diff(aa,axis=0)
a2 = np.mean(a1,axis=(0,2,3))
a1.shape

(14999, 30, 2, 3)

In [35]:
a2.shape

(30,)

In [36]:
a2

array([ 3.89995554e-05, -8.99342234e-05,  2.54219561e-05,  5.29058919e-06,
        2.86242511e-05, -3.39057064e-05,  6.36607898e-05, -8.22302674e-05,
        5.83417254e-05, -6.50008425e-05, -4.61601829e-05, -1.66776759e-05,
       -1.21735946e-05, -9.65002571e-06, -1.76760307e-05,  2.69110591e-05,
       -4.07497380e-05,  1.33757386e-04, -1.06964414e-04,  1.10037457e-04,
        2.37067790e-05, -2.98598347e-05,  2.76508914e-05, -4.30163803e-05,
        5.17889602e-05,  1.11295013e-04, -9.15641207e-05,  1.03627213e-04,
       -1.06801543e-04,  6.02123211e-05])